<?php
$page = "business-terms";
$title = "Business Terms of Service";
?>

<!DOCTYPE html>
<html lang="en" dir="ltr">

  <?php require "head.php"; ?>

  <body class="<?= $page; ?> preload">
    <?php require "nav.php"; ?>

    <div class="block block-hero legal">
      <div class="content"><h1>Business Terms of Service</h1></div>
    </div>

    <div class="block block-content">
      <div class="container">
        <div class="entry-content">
        			<p>Last Updated: July 6, 2018</p>
        <p>PLEASE READ THIS TERMS OF SERVICE AGREEMENT (THE&nbsp;<strong>“TERMS OF SERVICE”</strong>) CAREFULLY. BY SIGNING AN ORDER FORM OR UTILIZING SERVICES PROVIDED BY 18BIRDIES, LLC (“<strong>18BIRDIES</strong>”) THAT REFERENCES THESE TERMS OF SERVICE, LICENSEE REPRESENTS THAT (1) IT HAS READ, UNDERSTOOD, AND AGREES TO BE BOUND BY THE TERMS OF USE, AND (2) IT HAS THE AUTHORITY TO ENTER INTO THE TERMS OF USE PERSONALLY OR ON BEHALF OF THE COMPANY LICENSEE HAS NAMED AS THE USER, AND TO BIND THAT COMPANY TO THE TERMS OF USE. &nbsp;THE TERM&nbsp;<strong>“LICENSEE”</strong>&nbsp;REFERS TO THE INDIVIDUAL OR LEGAL ENTITY, AS APPLICABLE, IDENTIFIED AS THE USER REGISTERED ON THE WEBSITE. &nbsp;<strong>IF YOU DO NOT AGREE TO BE BOUND BY THE TERMS OF USE, YOU MAY NOT ACCESS OR USE THE 18BIRDIES WEBSITES OR SERVICES</strong>.</p>
        <p>Licensee’s use of, and participation in, the Service (as defined below) may be subject to additional terms (<strong>“Supplemental Terms”</strong>) and such Supplemental Terms will be presented to Licensee for its acceptance when Licensee elects to use the supplemental Service. &nbsp;If the Terms of Service are inconsistent with the Supplemental Terms, the Supplemental Terms shall control with respect to such Service. &nbsp;The Terms of Service and any applicable Supplemental Terms are referred to herein as the&nbsp;<strong>“Terms</strong>”.</p>
        <p>PLEASE NOTE THAT THE TERMS ARE SUBJECT TO CHANGE BY 18BIRDIES IN ITS SOLE DISCRETION AT ANY TIME. &nbsp;When changes are made, 18Birdies will make a new copy of the Terms of Service available at the Website and any new Supplemental Terms will be made available from within, or through, the affected Service on the Website. &nbsp;18Birdies will also update the “Last Updated” date at the top of the Terms of Service. 18Birdies may require Licensee to provide consent to the updated Terms in a specified manner before further use of the Website and/ or the Services is permitted. &nbsp;If Licensee does not agree to any change(s) after receiving a notice of such change(s), Licensee shall stop using the Website and/or the Services. Otherwise, Licensee’s continued use of the Website and/or Services constitutes Licensee’s acceptance of such change(s). &nbsp;PLEASE REGULARLY CHECK THE WEBSITE TO VIEW THE THEN-CURRENT TERMS.</p>
        <ol start="1">
          <li><strong>Service Terms</strong></li>
        </ol>
        <p><strong>1.1</strong>&nbsp;<strong>Service.&nbsp;</strong>Subject to the payment of applicable fees,18Birdies will provide the services ordered by Licensee (and accepted by 18Birdies) (“<strong>Service</strong>”) described on the 18Birdies pricing page or on mutually agreed upon order form (the pricing page and order form will each be referred to as, an “<strong>Order Form</strong>”) to Licensee (and additional end users specified by Licensee) for use, and 18Birdies hereby grants to Licensee and such end users a limited, revocable right and license to use and access the Service, solely for the purpose set forth on the Order Form. &nbsp;Except for Licensee’s (and its end users’) limited rights to use the Service as set forth herein, 18Birdies reserves all right, title and interest (including all intellectual property rights) in and to the Service.</p>
        <p><strong>1.2 Accounts</strong>. In order to access certain features of the Service, Licensee may be required to register for an account (“<strong>Account</strong>”). In registering an account on the Website, Licensee agrees: to (1) provide true, accurate, current and complete information about Licensee as prompted by the registration form (“<strong>Registration Data</strong>”); and (2) maintain and promptly update the Registration Data to keep it true, accurate, current and complete. &nbsp;Licensee accepts full responsibility for any unauthorized use of its Account and agrees to immediately notify 18Birdies of any actual or suspected unauthorized access to Licensee’s Account.</p>
        <ol start="2">
          <li><strong>Licensee Responsibilities</strong></li>
        </ol>
        <p><strong>2.1 Necessary Information.&nbsp;</strong>Licensee will provide, and/or Licensee shall cause its end users to provide, to 18Birdies all data, information, content, marks, works of authorship, Participant Information and any other materials necessary for 18Birdies to provide the Service in connection with Licensee’s events, tournaments or campaigns hereunder (collectively, “<strong>Licensee Materials</strong>”). Such Licensee Materials shall include, without limitation, tournament play information (e.g., scores), course information (e.g., yardage), names, dates and locations for all Licensee tournaments, any and all trademarks or service marks of Licensee and its tournaments, any and all information regarding entrants and participants in the Licensee tournaments (including, without limitation, any personally identifiable information of or relating to such individuals) (“<strong>Participant Information</strong>”), and any information or content in any listing created by, or on Licensee’s behalf, on the 18Birdies Properties. Licensee will obtain all third-party licenses, consents (including all consents from individuals as required by applicable law for 18Birdies to use Participant Information necessary for the provision of the Services) and permissions needed to provide the Licensee Materials to 18Birdies and to permit 18Birdies to use the Licensee Materials as set forth herein. &nbsp;Except for 18Birdies’ limited rights to use the Licensee Materials as set forth herein, Licensee reserves all right, title and interest (including all intellectual property rights) in and to the Licensee Materials.</p>
        <p><strong>2.2 Limitations.&nbsp;</strong>The rights granted to Licensee in the Terms are subject to the following restrictions: (a) Licensee shall not license, sell, rent, lease, transfer, assign, reproduce, distribute, host or otherwise commercially exploit the Website or Service (collectively, the “<strong>18Birdies Properties</strong>”) or any portion of 18Birdies Properties, including the Website; (b) Licensee shall not frame or utilize framing techniques to enclose any trademark, logo, or other 18Birdies Properties (including images, text, page layout or form) of 18Birdies; (c) Licensee shall not use any metatags or other “hidden text” using 18Birdies’s name or trademarks; (d) Licensee shall not modify, translate, adapt, merge, make derivative works of, disassemble, decompile, reverse compile or reverse engineer any part of 18Birdies Properties except to the extent the foregoing restrictions are expressly prohibited by applicable law; (e) Licensee shall not use any manual or automated software, devices or other processes (including but not limited to spiders, robots, scrapers, crawlers, avatars, data mining tools or the like) to “scrape” or download data from any web pages contained in the Website (except that we grant the operators of public search engines revocable permission to use spiders to copy materials from the Website for the sole purpose of and solely to the extent necessary for creating publicly available searchable indices of the materials, but not caches or archives of such materials); (f) Licensee shall not access 18Birdies Properties in order to build a similar or competitive website, application or service; (g) except as expressly stated herein, no part of 18Birdies Properties may be copied, reproduced, distributed, republished, downloaded, displayed, posted or transmitted in any form or by any means; and (h) Licensee shall not remove or destroy any copyright notices or other proprietary markings contained on or in 18Birdies Properties. Any future release, update or other addition to 18Birdies Properties shall be subject to the Terms. &nbsp;18Birdies, its suppliers and service providers reserve all rights not granted in the Terms. Any unauthorized use of 18Birdies Properties terminates the licenses granted by 18Birdies pursuant to the Terms.</p>
        <p><strong>2.3 Licensee Materials.&nbsp;</strong>Licensee grants (and, to the extent necessary, Licensee shall cause each end user to grant) 18Birdies the worldwide, perpetual, irrevocable, non-exclusive right and license to reproduce, adapt, distribute, publish, use, and share the Licensee Materials (i) in connection with the provision of the Service; and (ii) for its business purposes, including in order to improve the Service and to offer, advertise and promote its and third party products and services to end users. Without limiting the foregoing, the parties agree that 18Birdies may create de-identified and aggregated data or information resulting from Licensee’s (and its end users’) use of the Service, which may include individual and aggregated Participant Information and usage patterns (“<strong>De-Identified Information</strong>”). 18Birdies may use and analyze the Licensee Materials (including Participant Information and De-Identified Information) (a) to develop and improve 18Birdies’s products and services, and (b) for any lawful reason, including for commercial and noncommercial purposes. &nbsp;&nbsp;Licensee represents, warrants and covenants that it will not upload, transmit, or otherwise make available any Licensee Materials that are (1) unlawful, tortious, defamatory, vulgar, obscene, libelous, or racially , ethnically or otherwise objectionable; (2) violates, or encourages any conduct that would violate, any applicable law or regulation or would give rise to civil liability; (3) promotes discrimination, bigotry, racism, hatred, harassment or harm against any individual or group; (4) is violent or threatening, or promotes violence or actions that are threatening to any other person; or (5) promotes illegal or harmful activities.</p>
        <p><strong>2.4 SERVICE FEES.</strong>&nbsp;Licensee will pay to 18Birdies all fees for the Service purchased by Licensee, including all fees set forth on the Order Form. Licensee will be responsible for payment of such fees at the time it creates an Account and selects its subscription package. Licensee must provide 18Birdies with a valid credit card (Visa, MasterCard or any other issuer accepted by 18Birdies) (“<strong>Payment Provider</strong>”), or purchase order information as a condition to signing up for the Services. Licensee’s Payment Provider agreement governs its use of the designated credit card, and Licensee must refer to that agreement and not the Terms to determine its rights and liabilities. By providing 18Birdies with Licensee’s credit card number and associated payment information, Licensee agrees that 18Birdies is authorized to immediately invoice its Account for all fees and charges due and payable to 18Birdies hereunder and that no additional consent is required. &nbsp;Amounts set forth in invoices issued by 18Birdies shall be due net 30 days of invoice date, and shall exclude all sales, value added and other taxes, which will be the responsibility of Licensee. Interest will accrue on late payments at a rate of one and one-half percent (1.5%) per month or the maximum rate permitted by law, whichever is less, from the due date until paid. 18Birdies shall have the right to cease providing the Service in the event of any delinquent payments. All fees paid hereunder are nonrefundable, though 18Birdies reserves the right to issue refunds in its sole and absolute discretion.<strong>&nbsp;&nbsp;</strong>Licensee must notify 18Birdies in writing within fourteen (14) days after receiving its invoice of any dispute of the amounts invoiced, or such dispute will be deemed waived. Billing disputes should be sent to the following address: 505 14th #330 Oakland CA, 94612. 18Birdies uses Stripe, Inc. as its third party payment provider for payment services (e.g. card acceptance and related services). By making or accepting payments via the Services, Licensee agrees to be bound by the Stripe services agreement at:&nbsp;<a href="https://stripe.com/us/legal">https://stripe.com/us/legal</a>, Connected Account Agreement, which can be found here:&nbsp;<a href="https://stripe.com/us/connect-account/legal">https://stripe.com/us/connect-account/legal</a>, and Stripe’s privacy policy at:&nbsp;<a href="https://stripe.com/us/privacy">https://stripe.com/us/privacy</a>.</p>
        <ol start="3">
          <li><strong>Marketplace Terms</strong></li>
        </ol>
        <p>As part of the Service, 18Birdies may enable Licensee to market and sell goods and services through the Website and Service. When listing an item, Licensee agrees to comply with the following terms:</p>
        <p><strong>3.1 Listings</strong></p>
        <ol>
        <li>Licensee is responsible for the accuracy and content of the listing and item offered.</li>
        <li>Licensee’s listing may not be immediately searchable by keyword or category for several hours (or up to 24 hours in some circumstances).</li>
        <li>Licensee’s listings may not contain any unlawful, threatening, abusive, harassing, defamatory, libelous, deceptive, fraudulent, invasive of another’s privacy, tortious, obscene, offensive or profane material or content.</li>
        <li>18Birdies strives to create a marketplace where buyers can find what they are looking for. Therefore, the appearance or placement of listing in search and browse results will depend on a variety of factors, including, but not limited to:
        <ol>
        <li>Buyer’s location, search query, browsing sites, and history;</li>
        <li>Item’s location, listing format, price and shipping cost, terms of service, end time, history, and relevance to the user query.</li>
        <li>Licensee’s history, Licensee rating and feedback; and</li>
        <li>Number of listings matching the buyer’s query.</li>
        </ol>
        </li>
        </ol>
        <p>To drive a positive user experience, a listing may not appear in some search and browse results regardless of the sort order chosen by the buyer.</p>
        <p><strong>3.2 Marketplace Fees and Transactions</strong>. &nbsp;Licensee shall have sole discretion to set all prices for its goods and services offered in the 18Birdies Marketplace as 18Birdies is acting as Licensee’s agent for purposes of marketing, selling and distributing such goods and services. &nbsp;Users of the 18Birdies marketplace contract directly with the Licensee for Marketplace transactions. For clarity, 18Birdies will not be a party to any contracts between Licensee and such users in respect of such transactions. As Licensee’s agent, 18Birdies only facilitates these contracts by supplying a medium for the exchange of money and providing a venue to sell and distribute Licensee’s products and services.</p>
        <p>All payments for Marketplace transactions shall be processed through the 18Birdies Properties and not directly by Licensee. &nbsp;18Birdies shall retain its portion of the proceeds from such transactions and remit the balance to Licensee in accordance with the Supplemental Terms applicable to Marketplace transactions (“Marketplace Terms”). &nbsp;&nbsp;&nbsp;In addition, 18Birdies may charge Licensee and/or the purchaser additional fees for Marketplace transactions, which will be disclosed in the Marketplace Terms. 18Birdies may change the Marketplace Terms (including the fees it charges Licensee or any purchaser for Marketplace transactions) in its discretion, provided it posts the changes on the 18Birdies Properties and notifies Licensee by email at least fourteen (14) days prior to the effective date of any such pricing changes.</p>
        <p>Licensee shall be solely responsible for (a) providing 18Birdies with accurate information regarding the sales sales, value added and other use taxes to be collected by 18Birdies in connection with all Marketplace transactions, and (b) timely remittance of 18Birdies’s portion of such collected taxes to the applicable tax authority.</p>
        <p><strong>3.3 Release</strong>. 18Birdies expressly disclaims any liability that may arise between Licensee and any purchasers, or potential purchasers, of Licensee’s items. The marketplace on the 18Birdies Properties is only a venue for connecting users. Because 18Birdies is not involved in the actual contract between Licensee and purchasers or in the completion of the sale, in the event Licensee has a dispute with one or more purchasers, Licensee releases 18Birdies (and its officers, directors, agents, investors, subsidiaries and employees) from any and all claims, demands or damages (actual or consequential) of every kind and nature, known and unknown, suspected and unsuspected, disclosed and undisclosed, arising out of or in any way connected with such disputes.</p>
        <ol start="4">
          <li><strong>Community Builder Program</strong></li>
        </ol>
        <p>This Section 5 sets forth the applicable terms and conditions regarding 18Birdies Community Builder program (the “<strong>Program</strong>”). Under the Program, 18Birdies offers Licensee the opportunity to provide participants of Licensee’s tournaments and golfers on Licensee’s courses a unique referral ID or link (“<strong>Personal Link</strong>”) that a prospective user of 18Birdies’ consumer-facing mobile application (the “<strong>18Birdies App</strong>”) can use to download such app. &nbsp;For each Qualified Referral (defined below) generated through Licensee’s Personal Link, Licensee will receive a $5.00 USD commission as specified on 18Birdies’ Community Builder Program page (a “<strong>Commission</strong>”). 18Birdies reserves the right to terminate this Program at any time for any reason. &nbsp;If Licensee wishes to take part in the Program, Licensee is bound by these terms and conditions. If Licensee does not agree and abide by these terms and conditions in their entirety, then Licensee is not authorized to participate in the Program. &nbsp;Licensee may not participate in the Program where doing so would be prohibited by any applicable law or regulations. 18Birdies reserves the right to modify or amend at any time, these terms and conditions and the methods through which Commissions may be earned.</p>
        <p><strong>4.1 Program Participation</strong>.</p>
        <ol>
        <li><strong>Generally</strong>. To participate, Licensee shall provide a prospective end user of the 18Birdies App (a “<strong>Prospective User</strong>”) with Licensee’s Personal Link. The Prospective User must click on the Personal Link and complete the sign up in the same session. If the Prospective User does not complete the sign up in the same session, Licensee will not be credited for that referral and will not be eligible for the Commission, even if the Prospective User subsequently downloads the 18Birdies App and/or signs up for a paid membership on the 18Birdies App (a “<strong>Membership</strong>”). For purposes of clarification, completion of sign-up in the same session means clicking the Personal Link provided by Licensee, downloading the 18Birdies App and completing the app registration within a reasonable period of time, and without the Prospective User closing their Internet browser, clearing their Internet browser’s cookies, pressing the back button or closing the relevant app store application.</li>
        <li><strong>Eligibility</strong>. To be eligible for the Program and to receive Commissions, Licensee must: (i) have provided the Prospective User with their correct unique Personal Link; and (ii) have an Account in good standing with 18Birdies.</li>
        <li><strong>Qualified Referrals</strong>. A Qualified Referral means that all of the following conditions are met:
        <ol>
        <li>The Prospective User downloaded the 18Birdies App, completed the registration process and completed a qualified round, as validated by the 18Birdies App. If a Prospective User downloads the 18Birdies App or signs up for a Membership using any other link or method, the registration will not count as a Qualified Referral and Licensee will not be eligible for a Commission.</li>
        <li>The Prospective User had not previously downloaded and registered the 18Birdies App under any other email address or alias.</li>
        <li>The Prospective User (a) is at least 18 years old; (b) meets the eligibility requirements to become a Member of the 18Birdies App; (c) has consented to receiving communications from 18Birdies; and (d) is not an employee of Licensee, its service providers or any of its or their subsidiaries, affiliates or promotional agencies, including immediate family and household members.</li>
        </ol>
        </li>
        <li><strong>Commissions</strong>. Licensee will receive a Commission (as set forth on the Community Builder Program page) for each verified Qualified Referral generated through the Licensee’s Personal Link. &nbsp;The actual Commission will be determined by 18Birdies in its sole discretion as specified on the Program page. Licensee may attain an unlimited number of Qualified Referrals, but any Qualified Referral may be subject to review at any time by 18Birdies. 18Birdies has the right to determine in its sole discretion the legitimacy and validity of each such Qualified Referral. &nbsp;Commissions shall be paid at least monthly, provided, however, 18Birdies may in its discretion withhold payment of any Commissions until the balance owed to Licensee exceeds $50.00.</li>
        <li><strong>Verified Qualified Referrals</strong>. All Commissions are subject to verification. 18Birdies may delay a Commission for the purposes of investigation. 18Birdies may also refuse to verify and process any transaction 18Birdies deems, in its sole discretion, to be fraudulent, suspicious, or in violation of these Terms, or 18Birdies believes will impose potential liability on 18Birdies beyond what is reasonable for this Program, its subsidiaries, affiliates or any of their respective officers, directors, employees, representatives and agents. 18Birdies may cancel, amend or revoke the Commission at any time due to business considerations of circumstances beyond 18Birdies’s control. 18Birdies is not responsible for errors, omissions, malfunctions, interruptions, deletions, delays or failures of operations. All of 18Birdies’s decisions are final and binding, including decisions as to whether a Qualified Referral or Commission is verified.</li>
        </ol>
        <p><strong>4.2 Program Liability</strong>.</p>
        <ol>
        <li>By participating in the Program, Licensee agrees to indemnify, release and hold harmless 18Birdies, its service providers and their respective parent companies, affiliates and subsidiaries, together with their respective employees, directors, officers, licensees, licensors, shareholders, attorneys and agents including, without limitation, their respective advertising and promotion entities and any person or entity associated with the production, operation or administration of the Program (collective, the “<strong>Released Parties</strong>”), from any and all claims, actions, demands, damages, losses, liabilities, costs or expenses caused by, arising out of, in connection with, or related to their participation in the Program (including, without limitation, any property loss, damage, personal injury or death caused to any person(s)) and/or the awarding, receipt and/or use or misuse of the Program or any Commission.</li>
        <li><strong>Communications</strong>. 18Birdies will not be liable for: (i) late, lost, delayed, stolen, misdirected, incomplete, inaccurate, unreliable, garbled or unintelligible registrations, links, communications or affidavits, regardless of the method of transmission; (ii) data corruption, theft, destruction, unauthorized access to or alteration of account information or other materials; (iii) any injuries, losses or damages of any kind resulting from acceptance, possession or use of a Commission, or from participation in the Program, that were not reasonably foreseeable to 18Birdies at the relevant time; (iv) any printing, typographical, administrative or technological errors in any websites or materials associated with the Program; or (v) claims, demands, and damages in disputes among users of the Program.</li>
        </ol>
        <p><strong>4.3 Conduct</strong></p>
        <ol>
        <li>Promotion of Personal Links in a manner that would constitute or appear to constitute unsolicited commercial email or “spam” in 18Birdies’s sole discretion is expressly prohibited and may be grounds for immediate termination of Licensee’s Account and deactivation of the Personal Link.</li>
        <li><strong>Fraudulent and Suspicious Behavior</strong>. 18Birdies may prohibit Licensee from participating in the Program or receiving a Commission, in its sole discretion, if it determines that Licensee, either directly or indirectly, is attempting to undermine the fairness, integrity or legitimate operation of the Program in any way by cheating, hacking, deception or any other unfair practices. Use of any automated script, system or macro to participate in the Program or generate Qualified Referrals is strictly prohibited and will result in Licensee’s disqualification from the Program.</li>
        </ol>
        <ol start="5">
          <li><strong>Warranty; Disclaimer</strong></li>
        </ol>
        <p>THE SERVICE WILL CONFORM IN ALL MATERIAL RESPECTS TO THE DOCUMENTATION THEREFOR MADE AVAILABLE BY 18BIRDIES;&nbsp;<i>PROVIDED HOWEVER</i>, 18BIRDIES’ SOLE OBLIGATION, AND LICENSEE’S SOLE REMEDY IN THE EVENT OF ANY BREACH OF THE FOREGOING, SHALL BE 18BIRDIES’ REPERFORMANCE OR REPAIR OF THE SERVICE. 18BIRDIES MAKES NO OTHER WARRANTIES OR REPRESENTATIONS WITH RESPECT TO THE SERVICE TO LICENSEE, ANY END USER, OR TO ANY OTHER PERSON. &nbsp;TO THE EXTENT PERMITTED BY APPLICABLE LAW, 18BIRDIES DISCLAIMS ALL WARRANTIES, WHETHER EXPRESS, IMPLIED, OR STATUTORY, REGARDING THE SERVICE INCLUDING ANY WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, NON-INFRINGEMENT OF THIRD-PARTY RIGHTS, QUIET ENJOYMENT, AND ACCURACY.</p>
        <ol start="6">
          <li><strong>Indemnity; Limitation of Liability</strong></li>
        </ol>
        <p>Licensee will indemnify and hold harmless 18Birdies from and against any and all loss, liability, harm or expense suffered by 18Birdies arising out of or relating to (i) Licensee’s (including any end user’s) use or misuse of the Service, and/or actual or alleged breach of the terms of this Agreement (including, without limitation, (x) Licensee’s failure to remit sales or other use taxes pursuant to Section 2.4, (y) Licensee’s failure to provide accurate sales or other use tax information to 18Birdies in connection with Marketplace transactions, and (z) Licensee’s failure to timely remit taxes to the applicable taxing authority pursuant to Section 3.2), (ii) any claim or alleged claim brought by a purchaser or potential purchaser of Licensee’s goods and services offered through the 18Birdies Marketplace and/or (iii) any tournament conducted hereunder.</p>
        <p>18BIRDIES SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL OR CONSEQUENTIAL LIABILITIES ARISING FROM THE OPERATION (OR FAILURE TO OPERATE) OF THE SERVICE OR THIS AGREEMENT, INCLUDING LOSS OF PROFITS, LOSS OF DATA, OR LOSS OF BUSINESS, WHETHER OR NOT ADVISED OF SUCH POSSIBILITY. WITHOUT LIMITING THE FOREGOING, 18BIRDIES’ MAXIMUM AGGREGATE LIABILITY UNDER THIS AGREEMENT WILL NOT EXCEED THE TOTAL FEES PAID BY LICENSEE TO 18BIRDIES DURING THE TWELVE (12) MONTH PERIOD PRIOR TO THE DATE ON WHICH THE LIABILITY FIRST AROSE.</p>
        <ol start="7">
          <li><strong>Term and Termination</strong></li>
        </ol>
        <p>This Agreement commences on the Effective Date and will remain in effect until the termination of all Order Forms. &nbsp;Unless otherwise agreed, each Order Form will automatically renew at the end of its term for a period of twelve (12) months, unless the other party provides written notice of its intent to terminate such Order Form at least thirty (30) days prior to the end of the then-current term. Price increases for any such renewals shall only be effective if 18Birdies provides Licensee with written notice at least sixty (60) days prior to the end of the then-current term. &nbsp;Either party may terminate this Agreement immediately upon written notice to the other if the other party materially breaches (including, in the case of Licensee as the other party, in the event that any end user materially breaches) any provision of this Agreement and does not remedy the breach within thirty (30) days after receiving written notice;&nbsp;<i>provided, however</i>, (x) 18Birdies may terminate this Agreement immediately in the event Licensee breaches the representations and warranties in Section 2.3 and (y) 18Birdies may suspend Licensee’s Account and/or access to the Services if it reasonably suspects Licensee is in breach of these Terms. &nbsp;Without limiting the foregoing, 18Birdies may terminate this Agreement, for any reason or for no reason, upon sixty (60) days’ prior written notice. Upon the expiration or termination of this Agreement by 18Birdies for Licensee’s breach, any amounts owed to 18Birdies will become immediately due (including amounts that would have been due during the then-current term, but for such termination). &nbsp;In addition, upon any expiration or termination of this Agreement, (i) each party will promptly destroy or return any confidential information of the other party that remains in its possession or control, and (ii) those sections which by their nature should survive, shall survive the termination of this Agreement, including without limitation, ownership provisions, warranty disclaimers, indemnification and limitation of liability.</p>
        <ol start="8">
          <li><strong>Dispute Resolution</strong></li>
        </ol>
        <p><strong>8.1 Applicability of Arbitration Agreement</strong>. Licensee agrees that any dispute or claim relating in any way to Licensee’s access or use of the Website or any Service, or to any aspect of Licensee’s relationship with 18Birdies, will be resolved by binding arbitration, rather than in court, except that (1) Licensee may assert claims in small claims court if Licensee’s claims qualify; and (2) Licensee or 18Birdies may seek equitable relief in court for infringement or other misuse of intellectual property rights (such as trademarks, trade dress, domain names, trade secrets, copyrights, and patents).&nbsp;<strong>This agreement to arbitration (“Arbitration Agreement”) shall apply, without limitation, to all claims that arose or were asserted before the Effective Date of these Terms or any prior version of these Terms.</strong></p>
        <p><strong>8.2 Arbitration Rules and Forum.</strong>&nbsp;The arbitration will be conducted by JAMS. &nbsp;&nbsp;Disputes involving claims and counterclaims under $250,000, not inclusive of attorneys’ fees and interest, shall be subject to JAMS’s most current version of the Streamlined Arbitration Rules and procedures available at&nbsp;<a href="http://www.jamsadr.com/rules-streamlined-arbitration/">http://www.jamsadr.com/rules-streamlined-arbitration/</a>;&nbsp;all other claims shall be subject to JAMS’s most current version of the Comprehensive Arbitration Rules and Procedures, available at&nbsp;<a href="http://www.jamsadr.com/rules-comprehensive-arbitration/">http://www.jamsadr.com/rules-comprehensive-arbitration/</a>. If JAMS is not available to arbitrate, the parties will select an alternative arbitral forum.</p>
        <p><strong>8.3 Authority of Arbitrator</strong>. The arbitrator shall have exclusive authority to (a) determine the scope and enforceability of this Arbitration Agreement and (b) resolve any dispute related to the interpretation, applicability, enforceability or formation of this Arbitration Agreement including, but not limited to any claim that all or any part of this Arbitration Agreement is void or voidable. The arbitration will decide the rights and liabilities, if any, of Licensee and 18Birdies. &nbsp;&nbsp;The arbitration proceeding will not be consolidated with any other matters or joined with any other cases or parties. The arbitrator shall have the authority to grant motions dispositive of all or part of any claim. The arbitrator shall have the authority to award monetary damages and to grant any non-monetary remedy or relief available to an individual under applicable law, the arbitral forum’s rules, and the Terms (including the Arbitration Agreement). The arbitrator shall issue a written award and statement of decision describing the essential findings and conclusions on which the award is based, including the calculation of any damages awarded. &nbsp;The arbitrator has the same authority to award relief on an individual basis that a judge in a court of law would have. The award of the arbitrator is final and binding upon Licensee and us.</p>
        <p><strong>8.4 Waiver of Jury Trial</strong>. &nbsp;LICENSEE AND 18BIRDIES HEREBY WAIVE ANY CONSTITUTIONAL AND STATUTORY RIGHTS TO SUE IN COURT AND HAVE A TRIAL IN FRONT OF A JUDGE OR A JURY. Licensee and 18Birdies are instead electing that all claims and disputes shall be resolved by arbitration under this Arbitration Agreement, except as specified in Section 9.1 above. &nbsp;An arbitrator can award on an individual basis the same damages and relief as a court and must follow this Agreement as a court would. However, there is no judge or jury in arbitration, and court review of an arbitration award is subject to very limited review.</p>
        <p><strong>8.5 Waiver of Class or Other Non-Individualized Relief</strong>. &nbsp;ALL CLAIMS AND DISPUTES WITHIN THE SCOPE OF THIS ARBITRATION AGREEMENT MUST BE ARBITRATED ON AN INDIVIDUAL BASIS AND NOT ON A CLASS OR COLLECTIVE BASIS, ONLY INDIVIDUAL RELIEF IS AVAILABLE, AND CLAIMS OF MORE THAN ONE CUSTOMER OR USER CANNOT BE ARBITRATED OR CONSOLIDATED WITH THOSE OF ANY OTHER CUSTOMER OR USER. If a decision is issued stating that applicable law precludes enforcement of any of this subsection’s limitations as to a given claim for relief, than then claim must be severed from the arbitration and brought into the State or Federal Courts located in Oakland, California. All other claims shall be arbitrated.</p>
        <p><strong>8.6 Survival of Agreement</strong><i>.&nbsp;</i>This Arbitration Agreement will survive the termination of Licensee’s relationship with 18Birdies.</p>
        <ol start="9">
          <li><strong>General</strong></li>
        </ol>
        <p><strong>9.1 Confidential Information.</strong>&nbsp;The terms (but not the existence) of this Agreement, and any and all non-public information disclosed by either party to the other hereunder, shall be maintained by the receiving party as confidential (using no less than commercially reasonable efforts to protect such information from unauthorized disclosure) and may not be disclosed to a third party not under an obligation to maintain the confidentiality thereof, except as required by law, rule or regulation.</p>
        <p><strong>9.2 Non-Assignment.</strong>&nbsp;This Agreement may not be assigned without the prior written consent of the non-assigning party; except that 18Birdies may assign this Agreement to an affiliate or to a successor in connection with a merger, acquisition, or sale of all or substantially all of 18Birdies’s assets, stock or other equity interests.</p>
        <p><strong>9.3 Notices.</strong>&nbsp;All notices, consents, and approvals under this Agreement must be delivered in writing by overnight courier to the other party at the address set forth on the Order Form and will be effective upon receipt. The communications between Licensee and 18Birdies use electronic means, whether you visit 18Birdies Properties or send 18Birdies emails, or whether 18Birdies posts notices on 18Birdies Properties or communicates with you via email. For contractual purposes, you (1) consent to receive communications from Company in an electronic form; and (2) agree that all terms and conditions, agreements, notices, disclosures, and other communications that Company provides to you electronically satisfy any legal requirement that such communications would satisfy if it were to be in writing. &nbsp;The foregoing does not affect your statutory rights</p>
        <p><strong>9.4 Governing Law and Jurisdiction.</strong>&nbsp;This Agreement shall be governed by the law of the state of California, without reference to its conflicts of law rules. Any dispute, controversy or claim arising out of or relating to this Agreement that is not subject to the Arbitration Agreement, will be made exclusively in the state or federal courts located in Oakland, California and both parties hereby submit to the exclusive jurisdiction and venue of such courts.</p>
        <p><strong>9.5 Waiver; Severability.</strong>&nbsp;Any waiver of any provision of this Agreement must be given in writing and a waiver so given will not be deemed a waiver of any other provision or of such provision on any other occasion. If any provision of this Agreement is unenforceable, such provision will be severed from this Agreement and the remaining provisions will continue in full force and effect.</p>
        <p><strong>9.6 No Third Party Beneficiaries.</strong>&nbsp;This Agreement does not confer any right or benefit on any person who is not a party to it.</p>
        <p><strong>9.7 Force Majeure.</strong>&nbsp;A delay by either party in performing its obligations (except payment of fees) will not be a breach of this Agreement if beyond the reasonable control of the non-performing party. The affected party will use reasonable efforts, under the circumstances, to notify the other party of such circumstances and to resume performance as soon as possible.</p>
        <p><strong>9.7 Entire Agreement.</strong>&nbsp;This Agreement constitutes the entire agreement between the parties regarding its subject matter and supersedes all prior or contemporaneous agreements, understandings, and communication, whether written or oral. This Agreement may be amended only by a written document signed by both parties.</p>
        		</div>
      </div>
    </div>
<?php

require "footer.php";

?>
