<?php
$page = "privacy-policy";
$title = "Privacy Policy";
?>

<!DOCTYPE html>
<html lang="en" dir="ltr">

  <?php require "head.php"; ?>

  <body class="<?= $page; ?> preload">
    <?php require "nav.php"; ?>

    <div class="block block-hero legal">
      <div class="content"><h1>Privacy Policy</h1></div>
    </div>

    <div class="block block-content">
      <div class="container">
        <p>Last Updated: March 20, 2019</p>
        <p>This privacy policy (“<strong>Privacy Policy</strong>”) describes 18Birdies LLC’s (“<strong>18Birdies</strong>”, “<strong>we</strong>”, “<strong>us</strong>” or “<strong>our</strong>”) policies and procedures on the collection, use and disclosure of your personally identifiable information (“<strong>Personal Information</strong>”) when you use (a) www.18Birdies.com and all corresponding subdomains, web pages and websites associated with the foregoing URL (the “<strong>Site</strong>”), (b) the 18Birdies mobile application (the “<strong>App</strong>”), (c) 18Birdies Business Accounts and (d) any other content, applications, systems, features, functionality, software, information, products and services offered by us that link to this Privacy Policy (collectively, the “<strong>Services</strong>”).</p>
        <ol start="1">
          <li><strong>Introduction; General Terms</strong></li>
        </ol>
        <p>This Privacy Policy explains what information we collect in connection with your access to and/or use of the Site, App, and Services, how the information is used, and how and when we disclose such information. Please take a few minutes to read this Privacy Policy so that you understand how we treat your information.</p>
        <p>This Privacy Policy will remain in full force and effect, even if your access to, use of and/or participation in connection with the Services or any other particular service, feature, function, initiative, promotion, or activity offered on or through the Services terminates, expires, is suspended or deactivated for any reason. If you do not agree with this Privacy Policy, please do not participate in, access and/or use the Site, App, or any Services.</p>
        <p>This Privacy Policy governs only the information collected by us on or through your use of the Site, App, and Services, and does not cover any other information collected in any other manner or collected by any other third-party, unless specifically stated.</p>
        <ol start="2">
          <li><strong>Information We Collect About You</strong></li>
        </ol>
        <p><strong>Information you Provide Voluntarily</strong>. We collect the information you voluntarily provide to us. For example:</p>
        <ul>
        <li>In order to access and/or use the Services (e.g., account registration, game play, communication/networking features, purchases, reservations, promotions, etc.), we may require that you provide and/or otherwise make available to us certain information, which may include, among other things, your legal name, email address, physical address, telephone number, date of birth and gender.</li>
        <li>When you purchase products or services on our Site, we and/or our third-party payment processor will collect all information necessary to complete the transaction, including your name, billing information and shipping information.</li>
        <li>If you provide us feedback or contact us via email, we will collect your name and email address, as well as any other content included in the email, in order to send you a reply. When you post messages on our Site, the information contained in your posting will be stored on our servers and other users will be able to see it.</li>
        <li>When you participate in one of our surveys, we will collect the information you choose to submit to us.</li>
        <li>We also collect other types of Personal Information that you provide to us voluntarily, such as your operating system and version, and other requested information if you contact us via email regarding support for the Services.</li>
        <li>If you participate in a sweepstakes, contest or giveaway on our Site, we may ask you for your email address, name and phone number. These sweepstakes and contests are voluntary. &nbsp;We recommend that you read the rules for each sweepstakes and contest that you enter.</li>
        <li>We allow you to sign up and log in to the Services using accounts you create with third-party products and services, such as Facebook, Google and LinkedIn (collectively, “<strong>Third-Party Accounts</strong>”). If you access the Services with Third-Party Accounts we will collect information that you have agreed to make available such as your name, email address, profile information and preferences with the applicable Third-Party Account. This information is collected by the Third-Party Account provider and is provided to us under their privacy policies. You can generally control the information that we receive from these sources using the privacy settings in your Third-Party Account.</li>
        <li>We may also collect Personal Information at other points in the Services that state that Personal Information is being collected.</li>
        </ul>
        <p><strong>Information We Collect Automatically</strong>. When you access and/or use the Services, we automatically collect certain information through cookies, web beacons and other technologies and store it in our log files. &nbsp;This information includes anonymous identifiers, operating system and version, your Internet protocol (IP) address, pages you view on our Site, search terms you entered to arrive at our Site and other information regarding your access to and/or use of the Services. &nbsp;We may combine this information with other information that we have collected about you, including, where applicable, your username, name, and other Personal Information. Please see the section “Cookies and Other Tracking Mechanisms” below for more information.</p>
        <p><strong>Location Information</strong>. The Services may allow access to, or make available opportunities for you to view, and/or receive, certain content, products, services, information and other materials based, in whole or in part, upon your location (“<strong>Location Based Content</strong>”). In order to make Location Based Content available to you, the Services will determine your location using one or more points of data, reference and/or information associated with, among other things, the device you use to access and use the Services (a “<strong>Device</strong>”), including, without limitation, GPS, beacons, device software/features/services and other points of data, reference and information. If you have set your device to disable GPS, Bluetooth, WiFi or other location determining or assisting software, features or services, or do not authorize the Services to access your location data, the Services may not be able to determine your location and you may not be able to access, view and/or receive Location Based Content.</p>
        <p><strong>Address Book</strong>. We may periodically access and store your contact list and/or address book (and the information contained therein) on your Device to, among other things, find and keep track of mobile phone numbers of other users of the Services, and to allow you and us to send notifications (including, without limitation, invitations and requests) to your contacts, as well as other users of the Services, via SMS text, email and other methods. &nbsp;Prior to accessing your contact list or address book, we will ask for your consent to do so. If you do not consent to our access of such information, you may not be able to use certain functionality within the Service.</p>
        <p><strong>Information we obtain from third party sources</strong>. &nbsp;From time to time, we receive Personal Information about you from third party sources (including 18Birdies for Business customers), but only where we have received assurances from these third parties that they have either received your consent or are otherwise legally permitted or required to disclose your Personal Information to us. The types of information we may collect from third parties include your name and email address, phone number, gender and physical address. &nbsp;We use the information we receive from these third parties in order to provide Services to those third parties (for example, golf courses that are 18Birdies for Business customers can use the Services as a communication platform to communicate with you).</p>
        <ol start="3">
          <li><strong>How We Use Information</strong></li>
        </ol>
        <p><strong>Use of Personal Information.&nbsp;</strong>We may use your Personal Information for, among other things, the following purposes:</p>
        <ul>
        <li>To provide the Services to you, to communicate with you about your use of the Services, to respond to your inquiries, to fulfill your orders, and for other customer service purposes.</li>
        <li>To tailor the content and information that we may send or display to you, to offer location customization, or to otherwise personalize your experiences while using the Services.</li>
        <li>For marketing and promotional purposes. For example, we may send you emails about products or information we think may interest you. We may also use the information that we learn about you to help determine when and how to advertise our services on third-party websites, advertising networks and services, or to customize advertising to you or to customize your experience on our Site and the Services.</li>
        <li>To verify your eligibility to win a prize in a sweepstakes, contest or giveaway you have entered and to deliver that prize to you.</li>
        <li>For the prevention and detection of fraud or infringement of our or any third party’s rights.</li>
        <li>To better understand how users access and use our Service, both on an aggregated and individualized basis, in order to improve our Service, respond to user preferences, and for other research and analytical purposes.</li>
        <li>To diagnose service or technical problems.</li>
        <li>To ensure and maintain the security of the Services</li>
        <li>To comply with legal obligations or legal process.</li>
        <li>For any other purposes described in this Privacy Policy or disclosed at the time you provide us with the Personal Information.</li>
        </ul>
        <p><strong>Automated Decision Making</strong>. &nbsp;In some instances, our use of your Personal Information may result in automated decisions being taken (including profiling) that legally affect you or similarly significantly affect you. &nbsp;Automated decisions mean that a decision concerning you is made automatically on the basis of a computer determination (using software algorithms), without our human review. For example, we use automated decisions to match you with other users that meet criteria that you have specified to us and recommend tournaments and other events that we think may be of interest to you. &nbsp;We have implemented measures to safeguard the rights and interests of individuals whose Personal Information is subject to automated decision-making, including by allowing you to opt-in to features like Player Matching that utilize such decision-making. When we make an automated decision about you, you have the right to contest the decision, to express your point of view, and to require a human review of the decision. &nbsp;You can exercise this right by sending an email to us at support@18birdies.com.</p>
        <ol start="4">
          <li><strong>Sharing and Disclosure of Personal Information and Other Information</strong></li>
        </ol>
        <p><strong>Disclosure of User Status and Activity Information</strong>. In order to access and use the Services, you expressly acknowledge, understand and agree that the Services will automatically store, host, share, post, disseminate, disclose and/or publish certain information concerning your user account and profile (e.g., name, avatar/image, handicap, honors, achievements, user page details, etc.) and your corresponding use of the Services and related conduct, information and activities associated therewith (e.g., golf rounds played and related dates and times, golf scores, location, home courses, status updates, handicap, User Postings, etc.) in connection with the Services (collectively, “<strong>Status and Activity Information</strong>”). Status and Activity Information will be visible to all users of the Services (e.g., on golf leaderboards, your account page/profile, post and feed sections, etc.), including those users whom you have elected to follow and all other users of the Services that you have not friended and have no relationship with, unless you have disabled sharing of certain information within your account settings. &nbsp;However, at a minimum, your user name and profile image will be displayed to all users. Accordingly, you expressly acknowledge, understand and agree that all Status and Activity Information is public and may be globally viewed by all users of the Services.</p>
        <p>We make certain settings available to limit the sharing, availability or public nature of certain specific Status and Activity Information, and you can properly designate your preferences using such settings, then we will honor the choices you make about who can see certain specific Status and Activity Information (e.g., the accessibility and sharing of certain information only with your friends, as opposed to all users of the Services, etc.).</p>
        <p><strong>Third Party Products and Services</strong>. We may share your Personal Information with our third-party vendor partners in order to fulfill offers for products and services made available to you through the Services (e.g., tee times, activities, events, initiatives, promotions, trips, and merchandise) (“<strong>Third Party Products and Services</strong>”). &nbsp;Third Party Products and Services may be 18Birdies-branded, third-party-branded or co-branded and may be provided by us, our third-party vendor partners or their vendors. &nbsp;Third Party Products and Services may be made available to you through the Services and/or through a third-party vendor partner’s platform, website or service. For example, if you book a tee time through the Services, your information will be shared with a third-party tee time aggregator we contract with for such Services and the applicable golf course that the tee time aggregator has a relationship with, in order to complete your tee time booking. &nbsp;If such an offer requires us to share your Personal Information with one of our third-party vendor partners or another third party (for example, for fulfillment of the offer), such third party will be identified to you through the Services, along with such third party’s privacy policy. Please note that the use of such information by the third party is subject to their privacy policy. If you wish to opt-out of such third party’s future use of your Personal Information for marketing or other purposes, you will need to contact the third party directly.</p>
        <p><strong>Service Providers</strong>. In certain situations, we employ other companies and people to perform tasks on our behalf and share your information with them to provide that service. &nbsp;&nbsp;&nbsp;Except as stated in this Privacy Policy or unless we inform you otherwise, our service providers do not have any right to use the Personal Information we share with them beyond what we deem necessary to assist us in performing such tasks.</p>
        <p><strong>Additional Disclosures</strong>. There may be instances when we may access and/or disclose information without providing you a choice in the following circumstances: (a) to protect or defend our legal rights or property, or those of our affiliated companies, organizations and initiatives, and their employees, agents and contractors (including enforcement of our agreements); (b) to protect the safety and security of the Services and our users; (c) protect against fraud or for risk management purposes; (d) if we believe your actions violate the applicable terms of use agreement, this Privacy Policy, or any additional or supplemental terms applicable to the Services; or (e) to comply with law or legal process.</p>
        <p><strong>Corporate Restructuring.&nbsp;</strong>In the event that (a) we sell or transfer all or a part of our business, organization and/or assets (or those of an affiliated company, organization or initiative), or (b) we are otherwise involved in a bankruptcy, merger, joint venture, acquisition, stock sale, consolidation, spin-off, divestiture or any other similar or related transaction, we may transfer and otherwise provide your information to the party or parties involved in the transaction as part of the transaction, provided that we inform such party or parties that they must use your Personal Information only for the purposes disclosed in this privacy policy.</p>
        <p><strong>Aggregate and/or Non-identified Information</strong>. We may disclose aggregated and/or anonymized information collected through the Service and the use and disclosure of such aggregated and/or anonymized information by us or third-parties is not subject to any restrictions under this Privacy Policy.</p>
        <p><strong>Others</strong>. &nbsp;We may disclose your Personal Information to any other person with your consent to the disclosure.</p>
        <ol start="5">
          <li><strong>Access to your Personal Information and Your Privacy Rights</strong></li>
        </ol>
        <p>You may change your privacy preferences (e.g., ask us not to share your Personal Information with a particular third-party) by sending an email to us at support@18Birdies.com detailing your privacy request. Other privacy preferences (e.g., limiting location services), depending on the nature of the specific feature, functionality or offering, may be designated by modifying your account privacy, permissions and/or settings on your Device (if applicable) and the Services.</p>
        <p><i>Access, correct, update or request deletion</i>. If you wish to access, correct, update or request deletion of your Personal Information that you may not access directly through the Services, you can do so at any time by contacting us using the contact details provided under the “Contact us” section below.</p>
        <p><i>Object to processing, restrict processing or request portability</i>. If you are a resident of the European Union, you can object to processing of your Personal Information, ask us to restrict processing of your Personal Information, or request portability of your Personal Information. You can exercise these rights by sending an email to us at support@18birdies.com.</p>
        <p><i>Opt-out</i>. You have the right to opt-out of marketing communications we send you at any time. &nbsp;You can exercise this right by clicking on the “unsubscribe” or “opt-out” link in the marketing emails we send you or by sending an email to us at support@18birdies.com. Please note that “opt-out” and “unsubscribe” requests may not take effect immediately and may take a reasonable amount of time to receive, process and apply, during which time your information shall remain subject to the prior privacy settings. Further, also please note that in order to keep you informed about the operation of the Services, we may still send you administrative emails, notifications and announcements that are needed for the proper functioning and administration of the Services, including, without limitation, for the purposes described in Section 3 above, in connection with your use thereof.</p>
        <p><i>Withdraw consent</i>. If we have collected and processed your Personal Information with your consent, then you can withdraw your consent at any time. &nbsp;Withdrawing your consent will not affect the lawfulness of any processing we conducted prior to your withdrawal, nor will it affect processing of your Personal Information conducted in reliance on lawful processing grounds other than consent.</p>
        <p><i>Right to complain</i>. You have the right to complain to a data protection authority about our collection and use of your Personal Information. &nbsp;For more information, please contact your local data protection authority. (Contact details for data protection authorities in the European Economic Area are available&nbsp;<a href="http://ec.europa.eu/justice/data-protection/article-29/structure/data-protection-authorities/index_en.htm"><span class="s4">here</a>.)</p>
        <p>We respond to all requests we receive from individuals wishing to exercise their data protection rights in accordance with applicable data protection laws.</p>
        <ol start="6">
          <li><strong>Our Use of Cookies and Other Tracking Mechanisms</strong></li>
        </ol>
        <p>We and our third-party service providers may also use “cookies”, “embedded scripts”, web beacons, and other similar tracking technologies (collectively, “<strong>Tracking Technologies</strong>”) to collect information automatically as you use, access and/or otherwise interact with the Services. &nbsp;We may combine this information with other Personal Information we collect from you, and our third-party service providers may do so on our behalf.</p>
        <p><i>Cookies.&nbsp;</i>Cookies are alphanumeric identifiers that we transfer to your computer’s hard drive through your web browser for record-keeping purposes. Some cookies allow us to make it easier for you to navigate our Service, while others are used to enable a faster log-in process, to allow us to track your activities on the Services, or to otherwise enable features of the Services. Most web browsers automatically accept cookies, but if you prefer, you can edit your browser options to block them in the future. The Help portion of the toolbar on most browsers will tell you how to prevent your computer from accepting new cookies, how to have the browser notify you when you receive a new cookie, or how to disable cookies altogether. If you disable cookies, some features of the Site may not function.</p>
        <p><i>Clear GIFs, pixel tags and other technologies.&nbsp;</i>Clear GIFs are tiny graphics with a unique identifier, similar in function to cookies. In contrast to cookies, which are stored on your Device, clear GIFs are embedded invisibly on web pages. We may use clear GIFs (also known as web beacons, web bugs or pixel tags), in connection with the Site to, among other things, track the activities of Site visitors, help us manage content, and compile statistics about Site usage. We, or our service providers, may also use clear GIFs in HTML emails to you to help us track email response rates, identify when our emails are viewed, and track whether our emails are forwarded.</p>
        <p><i>LSOs.&nbsp;</i>We, or third-parties with whom we partner to provide certain features of the Service or to display advertising based upon your tracked activity, may use Local Storage Objects (“<strong>LSOs”</strong>) using technologies such as HTML5 or Flash to collect and store information. Various browsers may offer management tools for removing HTML5 LSOs.</p>
        <p><i>Third-party Analytics.&nbsp;</i>We use third-party analytics tools, such as Google Analytics, to collect, monitor and analyze collected information in order to improve functionality and user-friendliness, and to better tailor the Services to your needs. Accordingly, usage data is shared with Google, which has its own&nbsp;privacy policy&nbsp;addressing how it uses such information. We encourage you to review Google’s privacy policy to understand how Google uses such information.</p>
        <p>Please be aware that that if you limit the collection of certain information, you may not be able to use the Services, whether as it pertains to some or all of the Services, content, features and/or products made available in connection therewith.</p>
        <ol start="7">
          <li><strong>Interest-Based Advertising</strong></li>
        </ol>
        <p>The Services may also use a variety of third-party advertising networks, data exchanges, traffic measurement service providers, marketing analytics service providers, and other third-parties (collectively, “<strong>Third-Party Advertising Service Providers</strong>”), such as Google Ad Words and Facebook. We use Third-Party Advertising Service Providers to serve advertisements on, or in connection with, the Services, facilitate targeting of advertisements and/or measure and analyze advertising effectiveness and/or traffic on or in connection with the Services and any use thereof. Third-Party Advertising Service Providers may enable us to display advertisements based on your profile and corresponding use of the Services and other websites, services and platforms you have used or visited. Targeting services enable us to, among other things, help deliver advertisements or other content to you for products and services that you might be interested in, to prevent you from seeing the same advertisements too many times, and to conduct research regarding the usefulness of certain advertisements to you.</p>
        <p>Third-Party Advertising Service Providers may use&nbsp;Tracking Technologies to measure the effectiveness of their advertisements and to personalize advertising content to&nbsp;you. These third-party Tracking Technologies are governed by each third-party’s specific privacy policy, not this Privacy Policy. We may provide these third-party advertisers with information, including Personal Information, about you.</p>
        <p>Users in the United States may opt out of many third-party advertising networks. For example, you may go to the Digital Advertising Alliance (“<strong>DAA</strong>”)&nbsp;<a href="http://www.aboutads.info/choices/"><span class="s4">Consumer Choice Page</a>&nbsp;for information about opting out of interest-based&nbsp;advertising and choices regarding having information used by&nbsp;<a href="http://www.aboutads.info/participating"><span class="s4">DAA companies</a>. You may also go to the Network Advertising Initiative (“<strong>NAI</strong>”)&nbsp;<a href="http://www.networkadvertising.org/choices/"><span class="s4">Consumer Opt-Out Page</a>&nbsp;for information about opting out of interest-based advertising and choices regarding having information used by NAI members.</p>
        <p>Users in the European Union may also opt out of many third-party advertising networks. For example, you may go to the European Interactive Digital Advertising Alliance (“<strong>EDAA</strong>”)&nbsp;<a href="http://youronlinechoices.eu/"><span class="s4">Your Online Choices Page&nbsp;</a>for information about opting out of interest-based advertising and choices regarding having information used by&nbsp;<a href="http://www.youronlinechoices.com/goodpractice"><span class="s4">EDAA members</a>.</p>
        <p>Opting out from one or more companies listed on the DAA&nbsp;<a href="http://www.aboutads.info/choices/"><span class="s4">Consumer Choice Page</a>, the&nbsp;<a href="http://www.networkadvertising.org/choices/"><span class="s4">NAI Consumer Opt-Out Page</a> or the EDAA&nbsp;<a href="http://youronlinechoices.eu/"><span class="s4">Your Online Choices Page</a>&nbsp;will opt you out from those companies’ delivery of interest-based content or advertisements to you, but it does not mean you will no longer receive any advertising through our Site or on other websites. You may continue to receive advertisements, for example, based on the particular website that you are viewing (i.e., contextually based ads). Also, if your browsers are configured to reject cookies when you opt out on the DAA, NAI, or EDAA-related websites, your opt out may not be effective. Additional information is available on the DAA’s website at&nbsp;<a href="http://www.aboutads.info/"><span class="s4">www.aboutads.info</a>, the NAI’s website at&nbsp;<a href="http://www.networkadvertising.org/"><span class="s4">www.networkadvertising.org</a>, and the EDAA’s website at&nbsp;<a href="http://www.youronlinechoices.com/goodpractice"><span class="s4">www.youronlinechoices.com/goodpractice</a>.</p>
        <ol start="8">
          <li><strong>Minors</strong></li>
        </ol>
        <p>The Services are not directed toward children under 16 years of age, and we do not seek to collect Personal Information from children under 16, or knowingly allow such persons to become a registered user of the Services &nbsp;&nbsp;If we discover that we have collected Personal Information from a child under 16, we will take steps to remove that information from our systems. If you believe we inadvertently collected information from a child under 16 years of age, please contact support@18birdies.com.</p>
        <ol start="9">
          <li><strong>Your California Privacy Rights &amp; California Do Not Track Disclosure</strong></li>
        </ol>
        <p>If you are a resident of the State of California, we provide you with information on how to exercise your disclosure choice options with respect to use of your Personal Information by third parties for marketing purposes. If you are a California resident and wish to request information about how to exercise your third-party disclosure choices, please send a request by email to our Privacy Administrator at support@18Birdies.com detailing your privacy request. All requests must be labeled “Your California Privacy Rights” on the email subject line. For all requests, please clearly state that the request is related to “Your California Privacy Rights”, include your name, street address, city, state, zip code and email address (your street address is optional if you wish to receive a response to your request via email) and indicate your preference on how our response to your request should be sent (email or postal mail). We will not accept requests via the telephone, postal mail or by fax. We are not responsible for notices that are not labeled or sent properly, or do not have complete or legible information.</p>
        <p><strong><i>Currently, our systems do not recognize browser “do-not-track” requests</i></strong><i>.</i>&nbsp;You may, however, disable certain tracking (e.g., by disabling cookies) as discussed above in the section “Our Use of Cookies and Other Tracking Mechanisms”. For more information about tracking, please click&nbsp;<a href="http://www.allaboutdnt.com/"><span class="s4">here</a>.</p>
        <ol start="10">
          <li><strong>Transfer of Personal Information to the United States</strong></li>
        </ol>
        <p>If you visit, access, interact with and/or otherwise use the Services from a location outside the U.S., please be advised that any information you provide in connection with any such activity may be processed in and/or transferred to the U.S. and/or other territories and locations, where privacy protections may not be as comprehensive as those in the territory or location where you interact with or otherwise use the Services. We have taken appropriate safeguards to require that your Personal Information will remain protected in accordance with this Privacy Policy. These include implementing the European Commission’s Standard Contractual Clauses for transfers of Personal Information with our third-party service providers and partners and further details can be provided upon request. &nbsp;By using the Services, you affirmatively consent to the transfer, use, disclosure, provision, and other administration of your information as described herein.</p>
        <ol start="11">
          <li><strong>Legal Basis For Our Use (EEA visitors only)</strong></li>
        </ol>
        <p>If you are a resident of the European Economic Area, our legal basis for collecting and using the Personal Information described above will depend on the Personal Information concerned and the specific context in which we collect it. &nbsp;However, we will normally collect Personal Information from you only where we have your consent to do so, where we need the Personal Information to perform a contract with you, or where the processing is in our legitimate interests and not overridden by your data protection interests or fundamental rights and freedoms. &nbsp;In some cases, we may also have a legal obligation to collect Personal Information from you.</p>
        <p>If we ask you to provide Personal Information to comply with a legal requirement or to perform a contract with you, we will make this clear at the relevant time and advise you whether the provision of your Personal Information is mandatory or not (as well as of the possible consequences if you do not provide your Personal Information). &nbsp;Similarly, if we collect and use your Personal Information in reliance on our legitimate interests (or those of any third-party), we will make clear to you at the relevant time what those legitimate interests are.</p>
        <p>If you have questions about or need further information concerning the legal basis on which we collect and use your Personal Information for any specific processing activity, please contact us by sending an email to us at support@18birdies.com.</p>
        <ol start="12">
          <li><strong>Security</strong></li>
        </ol>
        <p>We have implemented appropriate physical and organizational measures to protect the information we collect from loss, misuse, and unauthorized access, disclosure, alteration, and destruction such as storing such information using third-party data centers that are routinely and independently audited against widely accepted security standards and encrypting data at rest and in transit. Please be aware that no data security measures can guarantee 100% security. You should take steps to protect against unauthorized access to your password and Device by, among other things, signing off after using a shared Device, choosing a robust password that nobody else knows or can easily guess, and keeping your login and password private. We are not responsible for any lost, stolen, or compromised passwords or for any activity on your account via unauthorized password activity.</p>
        <ol start="13">
          <li><strong>Data Retention</strong></li>
        </ol>
        <p>We retain Personal Information we collect from you where we have an ongoing legitimate business need to do so (for example, to provide you with Services you have requested or to comply with applicable legal, tax or accounting requirements). &nbsp;When we have no ongoing legitimate business need to process your Personal Information, we will either delete or anonymize it or, if this is not possible (for example, because your Personal Information has been stored in backup archives), then we will securely store your Personal Information and isolate it from any further processing until deletion is possible.</p>
        <ol start="14">
          <li><strong>Links to Third-Party Websites</strong></li>
        </ol>
        <p>We are not responsible for the practices employed by third-party websites linked to or from the Services, nor the information or content contained therein. Please remember that when you use a link to go from the Services to a third-party website, this Privacy Policy is no longer in effect. Your browsing and interaction on any third-party website, including those that have a link from the Services, is subject to that third-party website’s own rules and policies.</p>
        <ol start="15">
          <li><strong>Privacy Policy Changes</strong></li>
        </ol>
        <p>From time to time, we may modify this Privacy Policy to reflect industry initiatives, third party requirements or changes in the law, our information collection, use and disclosure practices, or the features and functionality of the Services, and such modifications shall be effective upon posting. In the event we update this Privacy Policy, we will update the “Last Updated” date above, and will provide notice on the Site and within the App. It is therefore important that you review this Privacy Policy regularly to ensure you are updated as to any changes. &nbsp;If we make any changes to this Privacy Policy that materially affect our practices with regard to the Personal Information we have previously collected from you, we will endeavor to notify you of such change by posting an announcement within the Services or contacting you directly via email or other means. If we are required by applicable data protection laws to seek your consent to any changes in use of your Personal Information described in our updated Privacy Policy, then we will do so.</p>
        <ol start="16">
          <li><strong>Accuracy</strong></li>
        </ol>
        <p>It is your responsibility to give us current, complete, accurate information, including Personal Information, and to keep such information up to date. We are not responsible for any problems or liability that may arise if you do not give us current, complete, or accurate information or Personal Information or you fail to update such information or Personal Information. We will reject and delete any entry that we believe in good faith to be false, fraudulent or inconsistent with this Privacy Policy.</p>
        <ol start="17">
          <li><strong>Contact Us</strong></li>
        </ol>
        <p>If you have any questions about our privacy practices or any of the terms or conditions of this Privacy Policy, please feel free to contact us at:</p>
        <address>18Birdies LLC<br>
        Attn: Customer Support<br>
        505 14th Street, Suite 330<br>
        Oakland, CA 94612<br>
        <a href="tel:844-833-7433">844-833-7433</a><br>
        <a href="mailto:support@18Birdies.com">support@18Birdies.com</a></address>
        <ol start="18">
          <li><strong>Sole Statement</strong></li>
        </ol>
        <p>This document is the sole statement of the Privacy Policy for the Services and no summary, restatement or other version thereof, or other privacy statement or policy, in any form, including, without limitation, machine-generated, is valid.</p>
  		</div>
    </div>
<?php

require "footer.php";

?>
