<?php
$page = "terms-of-service";
$title = "Terms of Service";
?>

<!DOCTYPE html>
<html lang="en" dir="ltr">

  <?php require "head.php"; ?>

  <body class="<?= $page; ?> preload">
    <?php require "nav.php"; ?>

    <div class="block block-hero legal">
      <div class="content"><h1>Terms of Service</h1></div>
    </div>

    <div class="block block-content">
      <div class="container">
        <p>Last Updated: April 29, 2019</p>
        <p>Please read these Terms of Service (“<strong>this Agreement</strong>”) between 18Birdies LLC (“<strong>18Birdies</strong>”, “<strong>we</strong>”, “<strong>us</strong>” or “<strong>our</strong>”) and you, an individual user (“<strong>you</strong>” or “<strong>your</strong>”). &nbsp;This Agreement applies to and governs your use of (a) www.18Birdies.com and all corresponding subdomains, web pages and websites associated with the foregoing URL (the “<strong>Site</strong>”), (b) the 18Birdies mobile application (the “<strong>App</strong>”), and (c) any other content, applications, systems, features, functionality, software, information, products and services offered by us that link to this Agreement (collectively the “<strong>Services</strong>”). By using the SITE, APP OR SERVICES, DOWNLOADING THE APP, COMPLETING THE REGISTRATION PROCESS AND/OR CLICKING THE “I ACCEPT” BUTTON, you understand and agree that (i) you have read and agree to be bound by this Agreement, and (ii) you are of legal age to form a binding contract with 18Birdies.</p>
        <p>Your use of, and participation in, certain Services may be subject to additional terms (“<strong>Additional Terms</strong>”), and such Additional Terms will either be listed in this Agreement or will be presented to you for your acceptance when you sign up to use the additional Service. To the extent that there is a conflict between this Agreement and the Additional Terms, the Additional Terms shall govern.</p>
        <p><strong>Please be aware that section 17 of this agreement, below, contains provisions governing how claims that you and we have against each other are resolved, including, without limitation, any claims that arose or were asserted prior to the effective date of this agreement. In particular, it contains an arbitration agreement which will, with limited exceptions, require disputes between us to be submitted to binding and final arbitration. Unless you opt out of the arbitration agreement: (1) you will only be permitted to pursue claims and seek relief against us on an individual basis, not as a plaintiff or class member in any class or representative action or proceeding; and (2) you are waiving your right to seek relief in a court of law and to have a jury trial on your claims.</strong></p>
        <p><strong>If you subscribe to 18Birdies Premium for a term (the “Initial Term”), then your subscription will be automatically renewed for additional periods of the same duration as the Initial Term at 18Birdies’ then-current fee for such services unless you decline to renew your subscription in accordance with section 13.</strong></p>
        <ol start="1">
        <li><strong>Term</strong></li>
        </ol>
        <p>This Agreement shall commence as of the date you accept it (in accordance with the preamble) and remain in full force and effect while you use the Services, unless terminated earlier in accordance with the terms herein. You may terminate your use of or registration for the Services at any time by closing your User Account (as defined below) and notifying us of your intent to terminate. 18Birdies may terminate your use of or registration for the Services at any time, for any or no reason, with or without prior notice or explanation, and without liability or obligation to you or any third party, including in the event you have breached this Agreement, or if we are required to by applicable law.</p>
        <ol start="2">
        <li><strong>Modifications</strong></li>
        </ol>
        <p>We may modify this Agreement at any time, for any reason, in our sole discretion. If we modify this Agreement, we will provide notice on the Site and within the App. We may also send you notice to the email address you provided. You are solely responsible for providing us with a current and accurate email address. In certain circumstances, we may require you to provide additional consent before any further use of the Site, App or Services is permitted. We recommend that you check back frequently and review this Agreement regularly so you are aware of the most current rights and obligations that apply to you.</p>
        <ol start="3">
        <li><strong>Compliance</strong></li>
        </ol>
        <p>By using the Services, you represent and warrant that (a) you are 16 years of age or older and acknowledge and agree that features, activities and other aspects of the Services may be subject to heightened age and/or other eligibility requirements; (b) your use of the Services does not violate any applicable law, rule or regulation; and (c) you shall make timely and satisfactory payment for any Services purchased by you. If you provide information that is untrue, inaccurate, incomplete, or we suspect that such information is untrue, inaccurate, or incomplete, we may suspend or terminate your registration (in whole or in part) and refuse any and all current or future use of the Services (or any portion thereof), in its sole discretion, with or without notice to you, and without liability or obligation to you.</p>
        <ol start="4">
        <li><strong>User Registration</strong></li>
        </ol>
        <p>In order to access and use the Services, we may require that you register for an account (“<strong>User Account</strong>”), create a unique username and password combination (“<strong>User Credentials</strong>”), and provide certain additional information, as prompted by our user registration process. You represent and warrant that all registration and account information you submit is truthful and accurate and that you shall maintain and promptly update the accuracy of such information. You may only have one User Account, and are responsible for maintaining the strict confidentiality of your User Credentials. You are responsible for any access to, or use of, the Services by you or any person or entity using your User Credentials or the device you use to access and use the Services (a “<strong>Device</strong>”), whether or not such access or use has been authorized by you or on your behalf, and whether or not such person or entity is your employee or agent, including, without limitation, any fee-­based transactions. It is therefore critical that you do not share your User Credentials with anyone. You agree to immediately notify 18Birdies of any unauthorized use of your User Credentials, User Account and/or Device, or any other breach of security, including, without limitation, if your Device is lost or stolen. It is your responsibility to (a) control the dissemination and use of your User Credentials, User Account, and Device; (b) update, maintain, and control access to your User Credentials, User Account, and Device; and (c) cancel your User Account. We reserve the right to deny access, use, and registration privileges to anyone if we believe there is a question about the identity of the person trying to access any account or element of the Services. 18Birdies shall not be responsible for any loss or damage arising from your failure to comply with this Section 4.</p>
        <ol start="5">
        <li><strong>Third-Party Platforms</strong></li>
        </ol>
        <p>Some of the Services may be dependent on and/or interoperate with third­ party owned and/or operated platforms and services (e.g., Facebook, Twitter, Google Play, PayPal, LinkedIn, Apple, etc.) (each, a “<strong>Third-Party Platform</strong>”) and may require that you be a registered member of such Third-Party Platforms and provide certain account credentials and other information in order to access such Services. Such Third-Party Platforms, in addition to providing application hosting, content distribution, support and other related services, may provide us with certain additional information about you. No Third-Party Platform through which you purchase the Services shall furnish any maintenance or support with respect to the Services, nor shall they address any third-party claims related to your use of the Services.</p>
        <ol start="6">
        <li><strong>Personal Information</strong></li>
        </ol>
        <p>We respect your privacy and the use and protection of your personally identifiable information. In the course of your use of the Services, you may be required to provide certain personal or personalized information to us (such information referred to hereinafter as “<strong>Personal Information</strong>”). Our information collection and use policies with respect to the privacy of such Personal Information are set forth in the Privacy Policy (<a href="https://18birdies.com/legal/privacy-policy/">https://18birdies.com/legal/privacy-policy/</a>). We encourage you to read the Privacy Policy, and to use it to help make informed decisions. You acknowledge and agree that you are solely responsible for the accuracy and content of Personal Information.</p>
        <ol start="7">
        <li><strong>Proprietary Rights</strong></li>
        </ol>
        <p>7.1.&nbsp;<strong>License</strong>. Subject to your compliance with this Agreement, 18Birdies grants you a limited, non-exclusive, non-transferable, non-sublicensable, revocable license to download, install, and use the App on a single Device that you own or control and to run the App solely for your own personal or internal business purposes. &nbsp;Furthermore, with respect to any App accessed through or downloaded from the Apple App Store (an “<strong>Apple App Store Sourced Application</strong>”), you will only use the Apple App Store Sourced Application (i) on an Apple-branded product that runs Apple’s proprietary operating system, and (ii) as permitted by the “Usage Rules” set forth in the Apple App Store Terms of Service.</p>
        <p>7.2&nbsp;<strong>Ownership</strong>. As between you and 18Birdies, 18Birdies exclusively owns all right, title and interest in and to the Site, App, and Services, and all content contained and/or made available on, through or in connection therewith (“<strong>Content</strong>”). The Site, App, Services, and Content are protected, without limitation, under U.S. Federal and State, as well as applicable foreign laws, rules, regulations and treaties.</p>
        <p>7.3.&nbsp;<strong>Restrictions</strong>. You must not alter, delete, or conceal any copyright, trademark, service mark or other notices contained on the Site, App, or Services, including, without limitation, notices on any Content you transmit, download, display, print, stream, or reproduce from the Services. Except as expressly authorized by 18Birdies or as set forth in Additional Terms (e.g., Services that allow for the use of embeddable or viral features, applications, etc.), you shall not, nor shall you allow any third-party (whether or not for your benefit or otherwise) to, reproduce, modify, create derivative works from, display, perform, publish, distribute, disseminate, broadcast or circulate to any third party (including, without limitation, on or via a third-party website or platform), or otherwise use, the App or any Content without the express, prior written consent of 18Birdies (or its owner, if 18Birdies is not the owner). Moreover, the framing or scraping of or in­line linking to the Site, Services, or any Content contained thereon and/or the use of web crawler, spidering or other automated means to access, copy, index, process and/or store any Content made available on or through the Services other than as expressly authorized by us in writing in advance is prohibited. You further agree to abide by exclusionary protocols (e.g., Robots.txt, Automated Content Access Protocol (ACAP), etc.) used in connection with the Services.</p>
        <ol start="8">
        <li><strong>User Conduct</strong></li>
        </ol>
        <p>You are solely responsible for your conduct in connection with the Services. We want to keep the Services safe and enjoyable for everyone and the use of the Services for unlawful or harmful activities is not allowed. You represent, warrant and agree that, while using the Services, you shall not:</p>
        <p>8.1 Intentionally or unintentionally engage in or encourage conduct that would violate any applicable law or rule, give rise to civil liability, or violate or infringe upon any intellectual property, proprietary, privacy, moral, publicity or other rights of ours or of any other person or entity;</p>
        <p>8.2 Submit, post, email, display, transmit, or otherwise make available on, through, or in connection with the Services any material that: (i) is, illegal, harmful, threatening, defamatory, deceptive, fraudulent, invasive of another’s privacy or publicity rights, harassing, contains explicit or graphic imagery or descriptions of excessive violence or sexual acts, links to adult content, or promotes discrimination, hatred or harm of any kind against any group or individual; (ii) makes available private information, or creates a security or privacy risk for any other person or entity; (iii) contains a software virus, worm, spyware, Trojan horse or other computer code, file or program designed to interrupt, impair, destroy or limit the functionality of any property; or (iv) is false, incorrect, misleading, or fraudulent information, including, without limitation, as it pertains to any golf-­related conduct, activities, achievements, initiatives, promotions, and/or opportunities;</p>
        <p>8.3 Intentionally or unintentionally engage in or encourage conduct that adversely affects 18Birdies, &nbsp;18Birdies’ affiliates, or any of their respective successors and assigns, directors, officers, employees, representatives, agents, licensors, advertisers, suppliers, operators or service providers, the Services, or causes duress, distress, or discomfort to us or anyone else, or discourages any person or entity from using all or any portion, features or functions of the Services, or from advertising, linking or becoming a supplier to us in connection with the Services;</p>
        <p>8.4 Without 18Birdies’ written agreement, use the Services for commercial purposes, whether compensated or not;</p>
        <p>8.5 Modify, disrupt, impair, alter or interfere with the use, features, function, operation or maintenance of the Services or the rights or use or enjoyment of the Services by any other user;</p>
        <p>8.6 Impersonate any person or entity, including, without limitation, a 18Birdies official, or falsely state or otherwise represent your affiliation with a person, entity or User Posting (as defined herein), transmit or otherwise make available on, through or in connection with the Services false or misleading indications of origin, information or statements of fact;</p>
        <p>8.7 Forge headers or otherwise manipulate identifiers in order to disguise the origin of any content transmitted on, through or in connection with the Services, including User Postings (as defined herein);</p>
        <p>8.8 Solicit passwords or personal identifying information for commercial or unlawful purposes from other users or engage in spamming, flooding, harvesting of email addresses or other personal information, “spidering”, “screen scraping”, “phishing”, “database scraping”, or any other activity with the purposes of obtaining lists of users or other information;</p>
        <p>8.9 Modify, reverse engineer, decompile or disassemble any part of the Services, whether in whole or in part, or create any derivative works from any part of the Services, or encourage, assist or authorize any other person to do so;</p>
        <p>8.10 Use the Services in a country that is subject to a U.S. Government embargo, or that has been designated by the U.S. Government as a “terrorist supporting” country; or</p>
        <p>8.11 Use the services if you are on any U.S. Government list of prohibited or restricted parties.</p>
        <ol start="9">
        <li><strong>Investigations.</strong></li>
        </ol>
        <p>18Birdies may investigate and take legal action against anyone who, in 18Birdies’ sole discretion, violates, or is suspected of violating, this Agreement, including, without limitation, reporting to law enforcement authorities. You acknowledge, consent, and agree that 18Birdies may access, preserve and disclose your account and registration information and any other content or information if required to do so by law or if based on a good faith belief that such access, preservation or disclosure is reasonably necessary to (i) comply with the legal process; (ii) enforce this Agreement; (iii) respond to claims that any content or information violates the rights of any third party; (iv) respond to your requests for customer or technical service; or (v) protect the rights, property or personal safety of 18Birdies, its users or any third parties. 18Birdies also reserves the right to remove the Services from Third-Party Platforms, which would limit your ability to re-download the Services.</p>
        <ol start="10">
        <li><strong>Export</strong></li>
        </ol>
        <p>You may not use, export, import, or transfer the App except as authorized by U.S. law, the laws of the jurisdiction in which you obtained the App, and any other applicable laws. &nbsp;In particular, but without limitation, the App may not be exported or re-exported (a) into any U.S. embargoed countries, or (b) to anyone on the U.S. Treasury Department’s list of Specially Designated Nationals or the U.S. Department of Commerce’s Denied Persons List or Entity List. By using the App, you represent and warrant that (i) you are not located in a country that is subject to a U.S. Government embargo, or that has been designated by the U.S. Government as a “terrorist supporting” country, and (ii) you are not listed on any U.S. Government list of prohibited or restricted parties. You also will not use the App for any purpose prohibited by U.S. law. &nbsp;You acknowledge and agree that App and the Services are subject to U.S. export control laws and regulations. You shall comply with these laws and regulations and shall not, without prior U.S. government authorization, export, re-export, or transfer 18Birdies’ products, services or technology, either directly or indirectly, to any country in violation of such laws and regulations.</p>
        <ol start="11">
        <li><strong>User Postings</strong></li>
        </ol>
        <p>11.1&nbsp;<strong>Defined; Acknowledgements</strong>. The Services may provide you and other users with an opportunity to participate in feeds, forums, communities and other message, comment and communication features and functionalities and may provide you with the opportunity to submit, post, email, display, transmit or otherwise make available comments, reviews, links, materials, ideas, opinions, messages, user information, and other information via the Services (each, a “<strong>User Posting</strong>”, and collectively, “<strong>User Postings</strong>”). The term “User Posting” also includes all of the information you submit or we may receive that is related to your User Posting. When you submit User Postings you may also be asked to provide information about you and your submission. This may include, without limitation, such things as your User Credentials, a descriptive title, information about the User Posting, your location and/or similar information. You further acknowledge and agree that all User Postings made by means of or in connection with any portion of the Services are public and that (a) you have no expectation of privacy in any User Posting, and (b) no confidential, fiduciary, contractually implied or other relationship is created between you and 18Birdies by reason of your transmitting a User Posting to any area of, or in connection with, the Services.</p>
        <p>11.2&nbsp;<strong>Responsibility; Liability</strong>. You understand, acknowledge and agree that all User Postings are the sole responsibility of the person from which such User Postings originated. This means that you are solely and entirely responsible for the consequences of all User Postings that you submit, upload, post, email, display, transmit or otherwise make available. User Postings do not reflect the views of 18Birdies, its affiliates, or any of their respective successors and assigns, directors, officers, employees, representatives or agents. You understand that by using the Services, you may be exposed to other user’s User Postings that could be offensive, indecent or objectionable and, as such, 18Birdies does not guarantee the accuracy, integrity, quality, or content of any User Postings. Under no circumstances shall 18Birdies be liable in any way for User Postings, including, without limitation, errors or omissions in any User Postings, or any loss or damage of any kind incurred as a result of any User Postings submitted, uploaded, posted, emailed, displayed, transmitted or otherwise made available.</p>
        <p>11.3&nbsp;<strong>Usage; Restrictions</strong>. The Services, including, without limitation, all User Posting features and functionality, is for personal purposes only and you may not submit, post, email, display, transmit or otherwise make available, in any manner, any User Posting that we deem to be an Unauthorized Posting (as defined herein). We have the right, but not the obligation, to review any User Posting and to delete, remove, move, edit or reject, without notice to you, for any reason or for no reason, any User Posting, including, without limitation, any Unauthorized Posting;&nbsp;<em>provided, however</em>, that 18Birdies shall have no obligation or liability to you or any third-party for failure to do so or for doing so in any particular manner. As used herein, the term “<strong>Unauthorized Posting</strong>” means any User Posting that is or may be construed as violating this Agreement, including, without limitation, Section 8 herein, or is deemed to be unacceptable to 18Birdies, as determined in 18Birdies’s sole discretion.</p>
        <p>11.4&nbsp;<strong>License; Usage</strong>. In connection with all User Postings you submit, post, email, display, transmit or otherwise make available, you grant to 18Birdies the unlimited, worldwide, non-­exclusive, irrevocable, perpetual and royalty-­free right, license, authorization, and permission, in any form or format, on or through any media or medium and with any technology or devices now known or hereafter developed or discovered, in whole or in part, to host, cache, store, maintain, use, reproduce, distribute, display, exhibit, perform, publish, broadcast, transmit, modify, prepare derivative works of, adapt, reformat, translate, and otherwise exploit all or any portion of your User Posting on the Services and any other websites, channels, services, and other distribution platforms, whether currently existing or developed in the future, for any purpose whatsoever (including, without limitation, for any promotional purposes) without accounting, notification, credit or other obligation to you, and the right to license and sub­license and authorize others to exercise any of the rights granted hereunder to 18Birdies, in our sole discretion. For the avoidance of doubt, the rights, licenses and privileges described in this Agreement and granted to 18Birdies shall commence immediately upon submission of your User Posting and shall continue thereafter perpetually and indefinitely, regardless of whether you use the Services as a registered user or not.</p>
        <p>11.5&nbsp;<strong>Rights; Representations</strong>. 18Birdies does not acquire any title or ownership rights in the User Postings that you submit and/or make available. After you submit, post, email, display, transmit or otherwise make available any User Posting, you continue to retain any such rights that you may have in such User Posting, subject to the rights, licenses and privileges granted herein. You also represent, warrant and covenant that you own the User Posting posted by you or otherwise have the right to grant the rights, licenses and privileges described in this Agreement and to perform and comply with all of the requirements set forth herein.</p>
        <p>11.6&nbsp;<strong>California Removal Rights</strong>. Registered users of Services who are California residents and are under 18 years of age may request and obtain removal of User Postings located on the Services that they themselves post by emailing us at: support@18Birdies.com. All requests must be labeled “California Removal Request” on the email subject line. All requests must provide a description of the content or information in your User Posting that you want removed and information reasonably sufficient to permit us to locate the material and, so that we can process your request and contact you if we have questions, include your registered username, name, street address, city, state, zip code and email address (your street address is optional if you wish to receive a response to your request via email), include the name and URL (if applicable) of the website, application or other interactive service and indicate your preference on how our response to your request should be sent (email or postal mail). We shall not accept requests via postal mail, telephone or facsimile. We are not responsible for notices that are not labeled or sent properly, and may not be able to respond if you do not provide complete information. We may also provide you the ability to remove individual specific User Postings that are comments by navigating to the comment, selecting the delete option when you hover over the right-hand side of the comment with your cursor and verifying the deletion request. Please note that any requests for removal do not ensure complete or comprehensive removal of the Content or information from the Services. For example, content that you have posted may be republished or reposted by another User or third party.</p>
        <ol start="12">
        <li><strong>Digital Millennium Copyright Act</strong></li>
        </ol>
        <p>18Birdies respects the intellectual property of others, and asks you to do the same. 18Birdies will (i) remove or disable access to material made available on or through the Services that 18Birdies believes in good faith, upon notice from an intellectual property owner or their agent, to be infringing the intellectual property of a third party; and (ii) remove any User Postings uploaded to the Services by “repeat infringers.” 18Birdies will consider you a “repeat infringer” if 18Birdies has received more than two takedown notices compliant with the provisions of 17 U.S.C. § 512 with respect to your User Postings. 18Birdies has discretion, however, to terminate your User Account after receipt of a single notification of claimed infringement or upon 18Birdies’ own determination.</p>
        <p>If you believe that any content made available on or through the Services has been used or exploited in a manner that infringes an intellectual property right you own or control, then promptly send a “Notification of Claimed Infringement” containing substantially the following information to 18Birdies’ Designated Agent identified below:</p>
        <ul>
          <li>A physical or electronic signature of a person authorized to act on behalf of the owner of the work(s) that is allegedly infringed;</li>
          <li>Identification of works or materials being infringed, or, if multiple works are covered by a single notification, then a representative list of such works;</li>
          <li>Identification of the specific material that is claimed to be infringing or to be the subject of infringing activity and that is to be removed or access to which is to be disabled, and information reasonably sufficient to permit 18Birdies to locate the material;</li>
          <li>Information reasonably sufficient to permit 18Birdies to contact you, such as an address, telephone number and, if available, an email address at which you may be contacted;</li>
          <li>A statement that you have a good faith belief that the use of the material in the manner complained of is not authorized by the copyright owner, its agent or the law; and</li>
          <li>A statement that the information in the notification is accurate, and under penalty of perjury, that you are authorized to act on behalf of the owner of an exclusive right that is allegedly infringed.</li>
        </ul>
        <p>Written notification of claimed infringement must be submitted to the following Designated Agent:</p>
        <address>18Birdies LLC<br>
        Attention: DMCA Copyright Agent<br>
        505 14th Street, Suite 330<br>
        Oakland, CA 94612<br>
        <a href="mailto:copyright@18birdies.com">copyright@18birdies.com</a></address>
        <p>18Birdies may share the Notification of Claimed Infringement with the user alleged to have infringed a right you own or control, and you hereby consent to 18Birdies making such disclosure.</p>
        <p>If you receive a notification from 18Birdies that material made available by you on or through the Services has been the subject of a Notification of Claimed Infringement, then you will have the right to provide 18Birdies a “Counter Notification.” To be effective, a&nbsp;Counter Notification&nbsp;must be in writing, provided to 18Birdies’ Designated Agent through one of the methods identified in this section, and include substantially the following information:</p>
        <ul>
          <li>Your physical or electronic signature;</li>
          <li>Identification of the material that has been removed or to which access has been disabled and the location at which the material appeared before it was removed or access to it was disabled;</li>
          <li>A statement under penalty of perjury that you have a good faith belief that the material was removed or disabled as a result of mistake or misidentification of the material to be removed or disabled; and</li>
          <li>Your name, address and telephone number, and a statement that you consent to the jurisdiction of Federal District Court for the judicial district in which the address is located, or if your address is outside of the United States, then for any judicial district in which 18Birdies may be found, and that you will accept service of process from the person who provided notification of infringement or an agent of such person.</li>
        </ul>
        <p>If you submit a Counter Notification to 18Birdies in response to a Notification of Claimed Infringement, then 18Birdies will promptly provide the person who provided the Notification of Claimed Infringement with a copy of your Counter Notification and inform that person that 18Birdies will replace the removed User Postings or cease disabling access to the User Postings in 10 business days following receipt of the Counter Notification, unless 18Birdies’ Designated Agent receives notice from the party that submitted the Notification of Claimed Infringement that such person has filed an action seeking a court order to restrain you &nbsp;from engaging in infringing activity relating to the material on the Services.</p>
        <p>The Copyright Act provides that any person who knowingly materially misrepresents under [Section 512 of the Copyright Act (17 U.S.C. § 512)] (1) that material or activity is infringing, or (2) that material or activity was removed or disabled by mistake or misidentification, will be liable for any damages, including costs and attorneys’ fees, incurred by the alleged infringer, by any copyright owner or copyright owner’s authorized licensee, or by a service provider, who is injured by such misrepresentation, as the result of [18Birdies] relying upon such misrepresentation in removing or disabling access to the material or activity claimed to be infringing, or in replacing the removed material or ceasing to disable access to it.</p>
        <p>18Birdies reserves the right to seek damages from any party that submits a Notification of Claimed Infringement or Counter Notification in violation of the law.</p>
        <ol start="13">
        <li><strong>Payment, Pricing, and Related Terms of Service</strong></li>
        </ol>
        <p>13.1&nbsp;<strong>Premium Subscription</strong>. &nbsp;In order to access certain features or functionality of the Services (including the ability to access certain content), you may be required to pay Premium membership fees. Premium membership fees, along with any required taxes, may be paid on a weekly, monthly or annual basis. All Premium membership fees are payable in advance. You agree to pay the membership fees, and other charges you incur in connection with your 18Birdies account, whether on a one-time or subscription basis. 18Birdies reserves the right to increase membership fees, any associated taxes, or to institute new fees at any time upon reasonable advance notice.</p>
        <p>13.2&nbsp;<strong>Other Fee-Based Services</strong>. The Services include the ability to make certain other fee-based transactions, including, without limitation, the ability to purchase goods and services (“<strong>Fee-Based Services</strong>”). In some cases, you may be required to make one payment to 18Birdies (for example, a deposit) and one or more subsequent payments to a third-party merchant or service provider to complete the transaction. &nbsp;Additional Terms may apply to your use of, access to and purchase of Fee-Based Services and will be presented to you at the time of purchase. Additional Terms may include terms and conditions between you and 18Birdies or terms and conditions from third party merchants or service providers who provide the Fee-Based Services. Such Additional Terms are incorporated herein by reference. Unless otherwise stated in the Additional Terms and Conditions for particular Fee-Based Services, the following terms and conditions shall apply to all Fee-Based Services:</p>
        <ul>
        <li>You may only use the Fee-Based Services if you are 18 years of age or older. You shall pay in full the prices and fees, including, without limitation, all applicable taxes (as more fully described below) for any purchases you, or anyone using the User Account registered to you, make via an Authorized Payment Method (as defined below).</li>
        <li>All transactions for Fee-Based Services are non-refundable. &nbsp;However, 18Birdies reserves the right to cancel any transaction in its sole discretion, in which case you will be given a full refund.</li>
        </ul>
        <p>13.3&nbsp;<strong>Payment Method and Terms</strong>. For all purchases, you will be charged at confirmation of purchase. In addition, for auto-renewing subscriptions, you will be charged within 24 hours prior to the end of the current period. The Services accept certain methods of payment which will be indicated at the time of purchase as forms of payment (each, an “<strong>Authorized Payment Method</strong>”), subject to certain restrictions, including, without limitation, territory restrictions, bank/payment card restrictions, spending limits, third party service provider restrictions or otherwise, which may prevent the processing of your order. If a transaction has been declined online due to payment card issues, please ensure all data is correct and resubmit. If the transaction is not accepted online, you will be unable to use that card for your transaction and should use another Authorized Payment Method. If a payment card company is being used for a transaction, 18Birdies may obtain a pre­approval from the applicable payment card company for an amount up to the amount of the order. All purchases are final once you click the “Submit” or similar button/link and billing to your payment card occurs at such time or shortly thereafter. If payment is not received by us from your credit, debit or charge card issuer or its agents or other payment service provider, you agree to promptly pay all amounts due upon demand by us. 18Birdies reserves the right to change any and all prices for any Services and other Content at any time, for any reason.</p>
        <p>13.4&nbsp;<strong>Auto Renewal</strong>. Your subscription will continue indefinitely until terminated in accordance with this Agreement. &nbsp;<strong>After your Initial Term, and again after any subsequent subscription period, your subscription will automatically commence on the first day following the end of such period (each a “Renewal Commencement Date”) and continue for an additional equivalent period, at 18Birdies’ then-current price for such subscription.</strong>&nbsp;&nbsp;You agree that your User Account will be subject to this automatic renewal feature unless you cancel your subscription prior to the Renewal Commencement Date. If you cancel your subscription, you may use your subscription until the end of your then-current subscription term, but you will not be eligible for a prorated refund of any portion of the subscription fee paid for the then-current subscription period. By subscribing, you authorize 18Birdies, including any payment processors, to charge you for the initial, and any renewal subscriptions. If 18Birdies does not receive payment from you or from a payment processor, (i) you agree to pay all amounts due on your User Account upon demand, and/or (ii) you agree that 18Birdies may either terminate or suspend your subscription and continue to attempt to charge you or a payment processor on your behalf until payment is received (upon receipt of payment, your User Account will be activated and for purposes of automatic renewal, your new subscription commitment period will begin as of the day payment was received).</p>
        <p>13.5&nbsp;<strong>Taxes</strong>. You are responsible for any taxes imposed on any subscription or Fee-Based transactions conducted on or in connection with the Services and applicable taxes will be added to the amount charged for the applicable transaction. Subscription and Fee-Based transactions in connection with the Services may include, without limitation, sales tax, use tax and any other applicable taxes, which may be based on various factors, including, without limitation, the billing address and tax rates in effect at the time your transaction is completed. &nbsp;No customers or users are eligible for tax exemptions for transactions made in connection with the Services.</p>
        <p>13.6&nbsp;<strong>Additional Terms and Conditions</strong>. 18Birdies may revise any or all of the fees and prices associated with the Services at any time for any or no reason. Further, 18Birdies does not guarantee that product descriptions or other content and products will be available, accurate, complete, reliable, current or error­-free. Descriptions and images of, and references to, products or services on or in connection with the subscription and Fee-Based Services do not imply 18Birdies’or any of its affiliates’ endorsement of such products or services. Moreover, 18Birdies and its third-party operational service providers reserve the right, with or without prior notice, for any or no reason, to change product descriptions, images, and references; to limit the available quantity of any product; to honor, or impose conditions on the honoring of, any coupon, coupon code, promotional code or other similar promotions; to bar any user from conducting any or all transaction(s); and/or to refuse to provide any user with any product. Further, if 18Birdies terminates your use of or registration to the Services because you have breached this Agreement, you shall not be entitled to a refund of any unused portion of any fees, payments or other consideration.</p>
        <p>13.7&nbsp;<strong>Virtual Currency</strong>. You may accrue virtual currency to your User Account through the Services. We determine and control the availability and nature of virtual currency in our sole discretion. You agree that we may terminate, modify, revalue, or make virtual currency more or less available without any notice or liability to you. Our virtual currency has no monetary value and no value outside the Services. Virtual currency may only be redeemed in the Services for limited purposes, including but not limited to certain promotions. Any unredeemed virtual currency earned on or before June 30, 2018 expired December 31, 2018. Any virtual currency earned after June 30, 2018 shall expire on the date set by us, or on the last day of the calendar year following the year in which such virtual currency was earned if no expiration date was communicated. Virtual currency may not be sold or exchanged for real money or for value outside of the Services. We provide virtual currency to you under a limited, personal, revocable, non-exclusive, non-transferable, non-sublicensable, and worldwide license to redeem virtual currency within the Services. Accordingly, except as set forth in the prior sentence, we own and retain all rights, title, and interest in and to the virtual currency in the Services. Virtual currency may not be sold, assigned, or transferred to any third-party under any circumstances unless we approve such transfer in writing. We will not be liable to you or required to provide refunds, benefits, or other compensation in connection with unredeemed virtual currency. If your Account is terminated for any reason, you may lose all virtual currency associated with your User Account.</p>
        <p>13.8&nbsp;<strong>Third Party Payment Processors</strong>. We use Stripe, Inc. to process payments. &nbsp;Stripe, Inc. may receive personal information from you. &nbsp;You are bound by the Stripe Connected Account Agreement, which can be found here: https://stripe.com/us/connect-account/legal</p>
        <p>13.9&nbsp;<strong>Disputes</strong>. If you have a complaint or dispute about a certain charge, or about a certain feature or product made available on or in connection with the subscription and Fee-Based Services, you must promptly notify 18Birdies customer service of such complaint or dispute by sending a detailed email to support@18Birdies.com.</p>
        <ol start="14">
        <li><strong>Customer Support</strong></li>
        </ol>
        <p>For assistance, questions or complaints please contact:</p>
        <address>18Birdies Customer Support<br>
        505 14th Street, Suite 330<br>
        Oakland, CA 94612<br>
        <a href="tel:844-833-7433">844-833-7433</a><br>
        <a href="mailto:support@18Birdies.com">support@18Birdies.com</a></address>
        <ol start="15">
        <li><strong> Indemnity</strong></li>
        </ol>
        <p>You agree to defend, indemnify and hold 18Birdies and its affiliates, and their respective successors and assigns, directors, officers, employees, representatives, agents, licensors, suppliers and service providers (the “<strong>18Birdies Parties</strong>”) harmless from any and all claims, liabilities, damages, losses, costs and expenses (including reasonable attorneys’ fees) (collectively, “<strong>Claims</strong>”), arising in any way out of or in connection with (a) your use of the Services, (b) your breach or violation of this Agreement, or (c) your User Postings. 18Birdies reserves the right to assume the exclusive defense and control of any matter otherwise subject to indemnification by you, and in such case, you agree to cooperate with 18Birdies’s defense of such Claim. This provision does not require you to indemnify the 18Birdies Parties for any unconscionable commercial practice by 18Birdies or for 18Birdies’ fraud, deception, false promise, misrepresentation or concealment, suppression or omission of any material fact in connection with the Site, App, or any Services provided hereunder.</p>
        <ol start="16">
        <li><strong>Disclaimer</strong></li>
        </ol>
        <p>16.1&nbsp;<strong>Generally.&nbsp;</strong>THE SERVICES, AND ALL CONTENT, PRODUCTS, SERVICES AND USER POSTINGS MADE AVAILABLE ON, THROUGH OR IN CONNECTION THEREWITH, ARE PROVIDED ON AN “AS IS” AND “AS AVAILABLE” BASIS, WITHOUT ANY REPRESENTATION, WARRANTY OR CONDITION OF ANY KIND, EXPRESS OR IMPLIED, OR ANY GUARANTY OR ASSURANCE THE SERVICES WILL BE AVAILABLE FOR USE, OR THAT ANY PRODUCTS, FEATURES, FUNCTIONS, SERVICES OR OPERATIONS WILL BE AVAILABLE OR PERFORM AS DESCRIBED. ALL IMPLIED REPRESENTATIONS, WARRANTIES AND CONDITIONS RELATING TO THE SERVICES AND THIS SITE, AND ALL CONTENT, PRODUCTS, SERVICES AND USER POSTINGS ARE HEREBY DISCLAIMED. Without limiting the foregoing, we are not responsible or liable for any malicious code, delays, inaccuracies, errors, or omissions arising out of your use of the Services. You understand, acknowledge and agree that you are assuming the entire risk as to the quality, accuracy, performance, timeliness, adequacy, completeness, correctness, authenticity, security and validity of any and all features and functions of the Services, including, without limitation, User Postings and Content associated with your use of the Services.</p>
        <p>16.2&nbsp;<strong>Third Party Products and Services.</strong>&nbsp;WE ARE NOT RESPONSIBLE AND HAVE NO LIABILITY WHATSOEVER FOR GOODS OR SERVICES YOU OBTAIN THROUGH THIRD PARTY SERVICE PROVIDERS OR OTHER WEB SITES, WEB PAGES, APPLICATIONS AND PLATFORMS (EVEN IF ACCESSED OR PURCHASED WITHIN, THROUGH OR IN CONNECTION WITH THE SERVICES), AND ANY SUCH PURCHASES ARE SUBJECT TO THEIR RESPECTIVE TERMS AND CONDITIONS OF USE. YOU ACKNOWLEDGE AND AGREE THAT PRODUCT/SERVICE SPECIFICATIONS AND OTHER INFORMATION HAVE EITHER BEEN PROVIDED BY THE APPLICABLE THIRD-PARTY VENDORS OR COLLECTED FROM PUBLICLY AVAILABLE SOURCES AND WE DO NOT MAKE ANY REPRESENTATIONS OR WARRANTIES AS TO THE ACCURACY OR RELIABILITY OF ANY SUCH INFORMATION. ACCORDINGLY, WE ENCOURAGE YOU TO MAKE WHATEVER INVESTIGATION YOU FEEL NECESSARY OR APPROPRIATE BEFORE PROCEEDING WITH ANY TRANSACTION WITH ANY OF THESE THIRD PARTIES AS SAME IS CONDUCTED AT YOUR SOLE RISK. FURTHER, WE DO NOT MAKE ANY REPRESENTATIONS OR WARRANTIES AS TO THE SECURITY OF ANY INFORMATION (INCLUDING, WITHOUT LIMITATION, CREDIT CARD AND OTHER PERSONAL INFORMATION) YOU MIGHT BE REQUESTED TO GIVE ANY SUCH THIRD-PARTY, AND YOU IRREVOCABLY WAIVE ANY CLAIM AGAINST US OR OUR AFFILIATES WITH RESPECT TO ANY SUCH TRANSACTION. WE ARE NOT RESPONSIBLE FOR ASSISTING YOU IN CORRECTING ANY PROBLEM YOU MAY EXPERIENCE WITH GOODS AND SERVICES PURCHASED THROUGH A THIRD-PARTY SERVICE PROVIDER, EVEN IF THE GOODS OR SERVICES ARE ACCESSED WITHIN, THROUGH OR IN CONNECTION WITH THE SERVICES. WE CANNOT ENSURE THAT YOU WILL BE SATISFIED WITH ANY PRODUCTS OR SERVICES THAT YOU PURCHASE FROM ANY THIRD-PARTY OPERATIONAL SERVICE PROVIDER AS THOSE ARE OWNED AND OPERATED BY INDEPENDENT ENTITIES. IN SOME CASES, YOU MAY BE REQUIRED TO DIRECT CUSTOMER SERVICE ISSUES RELATED TO GOODS OR SERVICES TO THE RELEVANT THIRD-PARTY OPERATIONAL SERVICE PROVIDER.</p>
        <p>16.3&nbsp;<strong>No Warranty of Timeliness or Availability</strong>. You further understand and acknowledge the capacity of the Services, in the aggregate and for each user, is limited. Consequently, some messages and transmissions, including, without limitation, User Postings, may not be processed in a timely fashion or at all, and some features or functions may be restricted or delayed or become completely inoperable. As a result, you acknowledge and agree that 18Birdies assumes no liability, responsibility or obligation to transmit, process, store, receive or deliver transactions or User Postings or for any failure or delay associated with any User Postings and you are hereby expressly advised not to rely upon the timeliness or performance of the Services for any transactions or User Postings. Some jurisdictions do not allow for the exclusion of certain warranties or certain limitations on damages and remedies, accordingly some of the exclusions and limitations described in this Agreement may not apply to you.</p>
        <p>16.4&nbsp;<strong>Limitation of Liability</strong><br>YOU UNDERSTAND AND AGREE THAT, TO THE FULLEST EXTENT PERMISSIBLE BY LAW, 18BIRDIES, ITS AFFILIATES, SUCCESSORS AND ASSIGNS, OFFICERS, DIRECTORS, EMPLOYEES, AGENTS, REPRESENTATIVES, LICENSORS, OPERATORS, SERVICE PROVIDERS, ADVERTISERS AND SUPPLIERS, SHALL NOT BE LIABLE FOR ANY CONSEQUENTIAL, INCIDENTAL, INDIRECT, SPECIAL OR PUNITIVE DAMAGES. IN NO EVENT SHALL 18BIRDIES’ LIABILITY TO YOU IN CONNECTION WITH THIS AGREEMENT EXCEED THE GREATER OF: (A) THE AMOUNTS PAID BY YOU DURING THE THREE (3) MONTH PERIOD IMMEDIATELY PRECEDING THE EVENT(S) GIVING RISE TO LIABILITY HEREUNDER; OR (B) $1,000 USD.</p>
        <ol start="17">
        <li><strong>Dispute Resolution</strong></li>
        </ol>
        <p><strong><em>Please read the following arbitration agreement in this Section (<strong>“Dispute Resolution”</strong>) carefully. It requires you to arbitrate disputes with 18Birdies and limits the manner in which you can seek relief from us.</em></strong></p>
        <p>17.1&nbsp;<strong>Applicability of Arbitration Agreement</strong><em>.</em>&nbsp;You agree that any dispute or claim relating in any way to your access or use of the Site, to any products sold or distributed through the Site, the Application, Services, or to any aspect of your relationship with 18Birdies, will be resolved by binding arbitration, rather than in court, except that (1) you may assert claims in small claims court if your claims qualify; and (2) you or 18Birdies may seek equitable relief in court for infringement or other misuse of intellectual property rights (such as trademarks, trade dress, domain names, trade secrets, copyrights, and patents). &nbsp;<strong>This Arbitration Agreement shall apply, without limitation, to all claims that arose or were asserted before the Effective Date of this Agreement or any prior version of this Agreement.</strong></p>
        <p>17.2&nbsp;<strong>Arbitration Rules and Forum</strong><em>.</em>&nbsp;&nbsp;The Federal Arbitration Act governs the interpretation and enforcement of this Arbitration Agreement. &nbsp;To begin an arbitration proceeding, you must send a letter requesting arbitration and describing your claim to 18Birdies, 505 14th Street, Suite 330, Oakland, CA 94612. The arbitration will be conducted by JAMS, an established alternative dispute resolution provider. &nbsp;Disputes involving claims and counterclaims under $250,000, not inclusive of attorneys’ fees and interest, shall be subject to JAMS’s most current version of the Streamlined Arbitration Rules and procedures available at&nbsp;<a href="http://www.jamsadr.com/rules-streamlined-arbitration/">http://www.jamsadr.com/rules-streamlined-arbitration/</a>; all other claims shall be subject to JAMS’s most current version of the Comprehensive Arbitration Rules and Procedures, available at&nbsp;<a href="http://www.jamsadr.com/rules-comprehensive-arbitration/">http://www.jamsadr.com/rules-comprehensive-arbitration/</a>. &nbsp;JAMS’s rules are also available at&nbsp;<a href="http://www.jamsadr.com/">www.jamsadr.com</a>&nbsp;or by calling JAMS at 800-352-5267. &nbsp;If JAMS is not available to arbitrate, the parties will select an alternative arbitral forum.</p>
        <p>17.3&nbsp;<strong>Authority of Arbitrator</strong>. The arbitrator shall have exclusive authority to (a) determine the scope and enforceability of this Arbitration Agreement and (b) resolve any dispute related to the interpretation, applicability, enforceability or formation of this Arbitration Agreement including, but not limited to any claim that all or any part of this Arbitration Agreement is void or voidable. &nbsp;The arbitration will decide the rights and liabilities, if any, of you and 18Birdies. The arbitration proceeding will not be consolidated with any other matters or joined with any other cases or parties. The arbitrator shall have the authority to grant motions dispositive of all or part of any claim. The arbitrator shall have the authority to award monetary damages and to grant any non-monetary remedy or relief available to an individual under applicable law, the arbitral forum’s rules, and this Agreement. The arbitrator shall issue a written award and statement of decision describing the essential findings and conclusions on which the award is based, including the calculation of any damages awarded. &nbsp;The arbitrator has the same authority to award relief on an individual basis that a judge in a court of law would have. The award of the arbitrator is final and binding upon you and us.</p>
        <p>17.4&nbsp;<strong>Waiver of Jury Trial</strong>. YOU AND 18BIRDIES HEREBY WAIVE ANY CONSTITUTIONAL AND STATUTORY RIGHTS TO SUE IN COURT AND HAVE A TRIAL IN FRONT OF A JUDGE OR A JURY. &nbsp;You and 18Birdies are instead electing that all claims and disputes shall be resolved by arbitration under this Arbitration Agreement, except as specified in Section 17.1 above. &nbsp;An arbitrator can award on an individual basis the same damages and relief as a court and must follow this Agreement as a court would. However, there is no judge or jury in arbitration, and court review of an arbitration award is subject to very limited review.</p>
        <p>17.5&nbsp;<strong>Waiver of Class or Other Non-Individualized Relief</strong>. &nbsp;ALL CLAIMS AND DISPUTES WITHIN THE SCOPE OF THIS ARBITRATION AGREEMENT MUST BE ARBITRATED ON AN INDIVIDUAL BASIS AND NOT ON A CLASS OR COLLECTIVE BASIS, ONLY INDIVIDUAL RELIEF IS AVAILABLE, AND CLAIMS OF MORE THAN ONE CUSTOMER OR USER CANNOT BE ARBITRATED OR CONSOLIDATED WITH THOSE OF ANY OTHER CUSTOMER OR USER. &nbsp;If a decision is issued stating that applicable law precludes enforcement of any of this subsection’s limitations as to a given claim for relief, than then claim must be severed from the arbitration and brought into the State or Federal Courts located in Oakland, California. All other claims shall be arbitrated.</p>
        <p>17.6&nbsp;<strong>Severability</strong><em>.&nbsp;</em>Except as provided in subsection 17.5, if any part or parts of this Arbitration Agreement are found under the law to be invalid or unenforceable, then such specific part or parts shall be of no force and effect and shall be severed and the remainder of the Arbitration Agreement shall continue in full force and effect.</p>
        <p>17.7&nbsp;<strong>Survival of Agreement</strong><em>.&nbsp;</em>This Arbitration Agreement will survive the termination of your relationship with 18Birdies.</p>
        <ol start="18">
        <li><strong>Miscellaneous</strong></li>
        </ol>
        <p>18.1.&nbsp;<strong>Final Agreement; Severability; Survival; Waiver</strong>. This Agreement and any applicable Additional Terms contain the entire understanding and agreement between you and 18Birdies concerning the Services and supersede any and all prior or inconsistent understandings relating to the Services and your use thereof. If any provision of this Agreement is held to be illegal, invalid or unenforceable, this shall not affect any other provisions and this Agreement shall be deemed amended to the extent necessary to make it legal, valid and enforceable. Any provision which must survive in order to allow us to enforce its meaning shall survive the termination of this Agreement; however, no action arising out of this Agreement or your use of the Services, regardless of form or the basis of the claim, may be brought by you more than one year after the cause of action has arisen (or if multiple causes, from the date the first such cause arose). The failure of 18Birdies to exercise or enforce any right or provision of this Agreement will not operate as a waiver of such right or provision.</p>
        <p>18.2&nbsp;<strong>Governing Law and Venue</strong>. This Agreement and your use of the Services is governed by, construed and enforced in accordance with the internal substantive laws of the State of California (notwithstanding the State’s conflict of laws provisions) applicable to contracts made, executed and wholly performed in California, and, for the purposes of any and all legal or equitable actions, you specifically agree and submit to the exclusive jurisdiction and venue of the State and Federal Courts situated in Oakland, California for any claims that cannot be resolved in accordance with Section 17 and agree you shall not object to such jurisdiction or venue on the grounds of lack of personal jurisdiction, forum non convenience or otherwise. &nbsp;IN ANY ACTION OR PROCEEDING COMMENCED TO ENFORCE ANY RIGHT OR OBLIGATION OF THE PARTIES UNDER THIS AGREEMENT, YOUR USE OF THE SERVICES OR WITH RESPECT TO THE SUBJECT MATTER HEREOF, YOU HEREBY WAIVE ANY RIGHT YOU MAY NOW HAVE OR HEREAFTER POSSESS TO A TRIAL BY JURY.</p>
        <p>18.3&nbsp;<strong>Notice</strong>. Where 18Birdies requires that you provide an email address, you are responsible for providing 18Birdies with your most current email address. &nbsp;In the event that the last email address you provided to 18Birdies is not valid, or for any reason is not capable of delivering to you any notices required/ permitted by the Terms, Company’s dispatch of the e-mail containing such notice will nonetheless constitute effective notice. &nbsp;You may give notice to 18Birdies at the following address: 505 14th Street, Suite 330, Oakland, CA 94612. Such notice shall be deemed given when received by 18Birdies by letter delivered by nationally recognized overnight delivery service or first class postage prepaid mail at the above address.</p>
        <p>18.4&nbsp;<strong>Assignment</strong>. This Agreement, and any rights, licenses and privileges granted herein, may not be transferred or assigned by you, but may be assigned or transferred by 18Birdies without restriction, notice or other obligation to you.</p>
        <p>18.5&nbsp;<strong>App Stores</strong>. You acknowledge and agree that the availability of the App and the Services is dependent on the third party from whom you received the Application license, e.g., the Apple App Store or Google Play (<strong>“App Store”</strong>). &nbsp;You acknowledge that this Agreement is between you and 18Birdies and not with the App Store. &nbsp;18Birdies, not the App Store, is solely responsible for the App, the content thereof, maintenance, support services, and warranty therefor, and addressing any claims relating thereto (e.g., product liability, legal compliance or intellectual property infringement). &nbsp;In order to use the App, you must have access to a wireless network, and you agree to pay all fees associated with such access. You also agree to pay all fees (if any) charged by the App Store in connection with the App. You agree to comply with, and your license to use the App is conditioned upon your compliance with, all applicable third-party terms of agreement (e.g., the App Store’s terms and policies) when using the App. You acknowledge that the App Store (and its subsidiaries) are third-party beneficiaries of this Agreement and will have the right to enforce it.</p>
      </div>
    </div>
<?php

require "footer.php";

?>
